(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [betree] *)

theory Betree
  imports
    Aeneas.Primitives
    begin
\m(* [betree::betree::List]
   Source: 'src/betree.rs', lines 17:0-20:1 *)
datatype betree_List_t (''t') =
| Betree_List_Cons 't of  betree_List_t 't ⇒ betree_List_t 't
| Betree_List_Nil betree_List_t 't(* [betree::betree::UpsertFunState]
                                     Source: 'src/betree.rs', lines 63:0-66:1 *)
datatype betree_UpsertFunState_t =
| Betree_UpsertFunState_Add u64 ⇒ betree_UpsertFunState_t
| Betree_UpsertFunState_Sub u64 ⇒ betree_UpsertFunState_t(* [betree::betree::Message]
                                                              Source: 'src/betree.rs', lines 69:0-117:1 *)
datatype betree_Message_t =
| Betree_Message_Insert u64 ⇒ betree_Message_t
| Betree_Message_Delete betree_Message_t
| Betree_Message_Upsert betree_UpsertFunState_t ⇒ betree_Message_t
(* [betree::betree_utils::load_internal_node]:
   Source: 'src/betree_utils.rs', lines 98:0-112:1 *)
axiomatization betree_utils_load_internal_node ::
  "u64 ⇒ result (betree_List_t (u64 × betree_Message_t))"

(* [betree::betree::load_internal_node]:
   Source: 'src/betree.rs', lines 36:0-38:1 *)
definition betree_load_internal_node
  (id : u64) : result (betree_List_t (u64 × betree_Message_t)) where
  betree_utils_load_internal_node id

(* [betree::betree_utils::store_internal_node]:
   Source: 'src/betree_utils.rs', lines 115:0-129:1 *)
axiomatization betree_utils_store_internal_node ::
  "u64 ⇒ betree_List_t (u64 × betree_Message_t) ⇒ result unit"

(* [betree::betree::store_internal_node]:
   Source: 'src/betree.rs', lines 41:0-43:1 *)
definition betree_store_internal_node
  (id : u64) (content : betree_List_t (u64 × betree_Message_t)) :
  result unit
  where
  betree_utils_store_internal_node id content

(* [betree::betree_utils::load_leaf_node]:
   Source: 'src/betree_utils.rs', lines 132:0-142:1 *)
axiomatization betree_utils_load_leaf_node ::
  "u64 ⇒ result (betree_List_t (u64 × u64))"

(* [betree::betree::load_leaf_node]:
   Source: 'src/betree.rs', lines 46:0-48:1 *)
definition betree_load_leaf_node
  (id : u64) : result (betree_List_t (u64 × u64)) where
  betree_utils_load_leaf_node id

(* [betree::betree_utils::store_leaf_node]:
   Source: 'src/betree_utils.rs', lines 145:0-155:1 *)
axiomatization betree_utils_store_leaf_node ::
  "u64 ⇒ betree_List_t (u64 × u64) ⇒ result unit"

(* [betree::betree::store_leaf_node]:
   Source: 'src/betree.rs', lines 51:0-53:1 *)
definition betree_store_leaf_node
  (id : u64) (content : betree_List_t (u64 × u64)) : result unit where
  betree_utils_store_leaf_node id content

(* [betree::betree::fresh_node_id]:
   Source: 'src/betree.rs', lines 55:0-59:1 *)
definition betree_fresh_node_id (counter : u64) : result (u64 × u64) where
  let counter1 = u64_add counter 1 :: u64 in Ok (counter, counter1)
(* [betree::betree::Leaf]
   Source: 'src/betree.rs', lines 167:0-171:1 *)
record betree_Leaf_t = id : u64
                       size : u64
datatype
  (* [betree::betree::Internal]
     Source: 'src/betree.rs', lines 156:0-161:1 *)