(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [betree]: type definitions *)

theory Betree.Types
  imports
    Aeneas.Primitives
    Betree.TypesExternal
    begin
\m(* [betree::betree::List]
   Source: 'src/betree.rs', lines 17:0-20:1 *)
datatype betree_List_t (''t') =
| Betree_List_Cons 't of  betree_List_t 't ⇒ betree_List_t 't
| Betree_List_Nil betree_List_t 't(* [betree::betree::UpsertFunState]
                                     Source: 'src/betree.rs', lines 63:0-66:1 *)
datatype betree_UpsertFunState_t =
| Betree_UpsertFunState_Add u64 ⇒ betree_UpsertFunState_t
| Betree_UpsertFunState_Sub u64 ⇒ betree_UpsertFunState_t(* [betree::betree::Message]
                                                              Source: 'src/betree.rs', lines 69:0-117:1 *)
datatype betree_Message_t =
| Betree_Message_Insert u64 ⇒ betree_Message_t
| Betree_Message_Delete betree_Message_t
| Betree_Message_Upsert betree_UpsertFunState_t ⇒ betree_Message_t(* [betree::betree::Leaf]
                                                                    Source: 'src/betree.rs', lines 167:0-171:1 *)
record betree_Leaf_t = id : u64
                       size : u64
datatype
  (* [betree::betree::Internal]
     Source: 'src/betree.rs', lines 156:0-161:1 *)
  datatype betree_Internal_t =
  | mk u64 of  u64 of  betree_Node_t of  betree_Node_t ⇒ betree_Internal_t
  
  (* [betree::betree::Node]
     Source: 'src/betree.rs', lines 179:0-184:1 *)
  and betree_Node_t =
  | Betree_Node_Internal betree_Internal_t ⇒ betree_Node_t
  | Betree_Node_Leaf betree_Leaf_t ⇒ betree_Node_t
(* [betree::betree::Params]
   Source: 'src/betree.rs', lines 187:0-199:1 *)
record betree_Params_t = min_flush_size : u64
                         split_size : u64(* [betree::betree::NodeIdCounter]
                                            Source: 'src/betree.rs', lines 201:0-203:1 *)
record betree_NodeIdCounter_t = next_node_id : u64(* [betree::betree::BeTree]
                                                     Source: 'src/betree.rs', lines 218:0-225:1 *)
record betree_BeTree_t =
  params : betree_Params_t
  node_id_cnt : betree_NodeIdCounter_t
  root : betree_Node_t
end
