(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [betree]: type definitions *)

theory Betree.Types
  imports
    Aeneas.Primitives
    Betree.TypesExternal
    begin
\m(* [betree::betree::List]
   Source: 'src/betree.rs', lines 17:0-20:1 *)
datatype betree_List_t (''t') =
| Betree_List_Cons 't of  betree_List_t 't ⇒ betree_List_t 't
| Betree_List_Nil betree_List_t 't(* [betree::betree::UpsertFunState]
                                     Source: 'src/betree.rs', lines 63:0-66:1 *)
datatype betree_UpsertFunState_t =
| Betree_UpsertFunState_Add u64 ⇒ betree_UpsertFunState_t
| Betree_UpsertFunState_Sub u64 ⇒ betree_UpsertFunState_t(* [betree::betree::Message]
                                                              Source: 'src/betree.rs', lines 69:0-117:1 *)
datatype betree_Message_t =
| Betree_Message_Insert u64 ⇒ betree_Message_t
| Betree_Message_Delete betree_Message_t
| Betree_Message_Upsert betree_UpsertFunState_t ⇒ betree_Message_t(* [betree::betree::Leaf]
                                                                    Source: 'src/betree.rs', lines 167:0-171:1 *)
record betree_Leaf_t = id : u64
                       size : u64
datatype
  (* [betree::betree::Internal]
     Source: 'src/betree.rs', lines 156:0-161:1 *)