(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap]: external types.
-- This is a template file: rename it to "TypesExternal.thy" and fill the holes. *)

theory Hashmap.TypesExternal_Template
  imports
    Aeneas.Primitives
    begin
\m
(* The state type used in the state-error monad *)
type state

end
