(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)

theory Hashmap.FunsExternal_Template
  imports
    Aeneas.Primitives
    Hashmap.Types
    begin
\m
(* [hashmap::utils::serialize]:
   Source: 'tests/src/hashmap.rs', lines 324:4-326:5 *)
axiomatization utils_serialize ::
  "HashMap_t u64 ⇒ state ⇒ result (state × unit)"

(* [hashmap::utils::deserialize]:
   Source: 'tests/src/hashmap.rs', lines 329:4-331:5 *)
axiomatization utils_deserialize ::
  "state ⇒ result (state × (HashMap_t u64))"

end
