(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap]: type definitions *)

theory Hashmap.Types
  imports
    Aeneas.Primitives
    Hashmap.TypesExternal
    begin
\m(* [hashmap::AList]
   Source: 'tests/src/hashmap.rs', lines 28:0-31:1 *)
datatype AList_t (''t') =
| AList_Cons usize of  't of  AList_t 't ⇒ AList_t 't
| AList_Nil AList_t 't(* [hashmap::Fraction]
                         Source: 'tests/src/hashmap.rs', lines 44:0-47:1 *)
record Fraction_t = dividend : usize
                    divisor : usize(* [hashmap::HashMap]
                                      Source: 'tests/src/hashmap.rs', lines 50:0-62:1 *)
record HashMap_t (''t') =
  num_entries : usize
  max_load_factor : Fraction_t
  max_load : usize
  saturated : bool
  slots : alloc_vec_Vec (AList_t 't)
end
