(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [adt_borrows] *)

theory AdtBorrows
  imports
    Aeneas.Primitives
    begin
\m(* [adt_borrows::SharedWrapper]
   Source: 'tests/src/adt-borrows.rs', lines 7:0-7:35 *)
abbreviation SharedWrapper_t (''t') = 't
(* [adt_borrows::{adt_borrows::SharedWrapper<'a, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 10:4-12:5 *)
definition sharedWrapper_create
  ('t) (x : 't) : result (SharedWrapper_t 't) where
  Ok x

(* [adt_borrows::{adt_borrows::SharedWrapper<'a, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 14:4-16:5 *)
definition sharedWrapper_unwrap
  ('t) (self : SharedWrapper_t 't) : result 't where
  Ok self

(* [adt_borrows::use_shared_wrapper]:
   Source: 'tests/src/adt-borrows.rs', lines 19:0-24:1 *)
definition use_shared_wrapper : result unit where
  let w = sharedWrapper_create 0 :: i32 in
  let p = sharedWrapper_unwrap w in
  massert (0 :: i32 = p)
(* [adt_borrows::SharedWrapper1]
   Source: 'tests/src/adt-borrows.rs', lines 26:0-28:1 *)
record SharedWrapper1_t (''t') = x : 't
(* [adt_borrows::{adt_borrows::SharedWrapper1<'a, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 31:4-33:5 *)
definition sharedWrapper1_create
  ('t) (x : 't) : result (SharedWrapper1_t 't) where
  Ok (| x |)

(* [adt_borrows::{adt_borrows::SharedWrapper1<'a, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 35:4-37:5 *)
definition sharedWrapper1_unwrap
  ('t) (self : SharedWrapper1_t 't) : result 't where
  Ok x self

(* [adt_borrows::use_shared_wrapper1]:
   Source: 'tests/src/adt-borrows.rs', lines 40:0-45:1 *)
definition use_shared_wrapper1 : result unit where
  let w = sharedWrapper1_create 0 :: i32 in
  let p = sharedWrapper1_unwrap w in
  massert (0 :: i32 = p)
(* [adt_borrows::SharedWrapper2]
   Source: 'tests/src/adt-borrows.rs', lines 47:0-50:1 *)
record SharedWrapper2_t (''t') = x : 't
                                 y : 't
(* [adt_borrows::{adt_borrows::SharedWrapper2<'a, 'b, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 53:4-55:5 *)
definition sharedWrapper2_create
  ('t) (x : 't) (y : 't) : result (SharedWrapper2_t 't) where
  Ok (| x, y |)

(* [adt_borrows::{adt_borrows::SharedWrapper2<'a, 'b, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 57:4-59:5 *)
definition sharedWrapper2_unwrap
  ('t) (self : SharedWrapper2_t 't) : result ('t × 't) where
  Ok (x self, y self)

(* [adt_borrows::use_shared_wrapper2]:
   Source: 'tests/src/adt-borrows.rs', lines 62:0-69:1 *)
definition use_shared_wrapper2 : result unit where
  let w = sharedWrapper2_create 0 :: i32 1 :: i32 in
  let (px, py) = sharedWrapper2_unwrap w in
  let _ = massert (0 :: i32 = px) in
  massert (1 :: i32 = py)
(* [adt_borrows::MutWrapper]
   Source: 'tests/src/adt-borrows.rs', lines 71:0-71:36 *)
abbreviation MutWrapper_t (''t') = 't
(* [adt_borrows::{adt_borrows::MutWrapper<'a, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 74:4-76:5 *)
definition mutWrapper_create
  ('t) (x : 't) : result ((MutWrapper_t 't) × (MutWrapper_t 't ⇒ 't)) where
  Ok (x, fun (ret : MutWrapper_t 't) => ret)

(* [adt_borrows::{adt_borrows::MutWrapper<'a, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 78:4-80:5 *)
definition mutWrapper_unwrap
  ('t) (self : MutWrapper_t 't) : result ('t × ('t ⇒ MutWrapper_t 't)) where
  let back = fun (ret : 't) => ret in Ok (self, back)

(* [adt_borrows::{adt_borrows::MutWrapper<'a, T>}::id]:
   Source: 'tests/src/adt-borrows.rs', lines 82:4-84:5 *)
definition mutWrapper_id
  ('t) (self : MutWrapper_t 't) :
  result ((MutWrapper_t 't) × (MutWrapper_t 't ⇒ MutWrapper_t 't))
  where
  let back = fun (ret : MutWrapper_t 't) => ret in Ok (self, back)

(* [adt_borrows::use_mut_wrapper]:
   Source: 'tests/src/adt-borrows.rs', lines 87:0-93:1 *)
definition use_mut_wrapper : result unit where
  let (w, create_back) = mutWrapper_create 0 :: i32 in
  let (p, unwrap_back) = mutWrapper_unwrap w in
  let p1 = i32_add p 1 :: i32 in
  let x = create_back (unwrap_back p1) in
  massert (x = 1 :: i32)

(* [adt_borrows::use_mut_wrapper_id]:
   Source: 'tests/src/adt-borrows.rs', lines 95:0-97:1 *)
definition use_mut_wrapper_id
  ('t) (x : MutWrapper_t 't) :
  result ((MutWrapper_t 't) × (MutWrapper_t 't ⇒ MutWrapper_t 't))
  where
  let (mw, id_back) = mutWrapper_id x in
  let back = fun (ret : MutWrapper_t 't) => id_back ret in
  Ok (mw, back)
(* [adt_borrows::MutWrapper1]
   Source: 'tests/src/adt-borrows.rs', lines 99:0-101:1 *)
record MutWrapper1_t (''t') = x : 't
(* [adt_borrows::{adt_borrows::MutWrapper1<'a, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 104:4-106:5 *)
definition mutWrapper1_create
  ('t) (x : 't) :
  result ((MutWrapper1_t 't) × (MutWrapper1_t 't ⇒ 't))
  where
  let back = fun (ret : MutWrapper1_t 't) => x ret in Ok ((| x |), back)

(* [adt_borrows::{adt_borrows::MutWrapper1<'a, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 108:4-110:5 *)
definition mutWrapper1_unwrap
  ('t) (self : MutWrapper1_t 't) :
  result ('t × ('t ⇒ MutWrapper1_t 't))
  where
  let back = fun (ret : 't) => (| x = ret |) in Ok (x self, back)

(* [adt_borrows::{adt_borrows::MutWrapper1<'a, T>}::id]:
   Source: 'tests/src/adt-borrows.rs', lines 112:4-114:5 *)
definition mutWrapper1_id
  ('t) (self : MutWrapper1_t 't) :
  result ((MutWrapper1_t 't) × (MutWrapper1_t 't ⇒ MutWrapper1_t 't))
  where
  Ok (self, fun (ret : MutWrapper1_t 't) => ret)

(* [adt_borrows::use_mut_wrapper1]:
   Source: 'tests/src/adt-borrows.rs', lines 117:0-123:1 *)
definition use_mut_wrapper1 : result unit where
  let (w, create_back) = mutWrapper1_create 0 :: i32 in
  let (p, unwrap_back) = mutWrapper1_unwrap w in
  let p1 = i32_add p 1 :: i32 in
  let x = create_back (unwrap_back p1) in
  massert (x = 1 :: i32)

(* [adt_borrows::use_mut_wrapper1_id]:
   Source: 'tests/src/adt-borrows.rs', lines 125:0-127:1 *)
definition use_mut_wrapper1_id
  ('t) (x : MutWrapper1_t 't) :
  result ((MutWrapper1_t 't) × (MutWrapper1_t 't ⇒ MutWrapper1_t 't))
  where
  mutWrapper1_id x
(* [adt_borrows::MutWrapper2]
   Source: 'tests/src/adt-borrows.rs', lines 129:0-132:1 *)
record MutWrapper2_t (''t') = x : 't
                              y : 't
(* [adt_borrows::{adt_borrows::MutWrapper2<'a, 'b, T>}::create]:
   Source: 'tests/src/adt-borrows.rs', lines 135:4-137:5 *)
definition mutWrapper2_create
  ('t) (x : 't) (y : 't) :
  result ((MutWrapper2_t 't) × (MutWrapper2_t 't ⇒ 't) × (MutWrapper2_t 't
    ⇒ 't))
  where
  let back'a = fun (ret : MutWrapper2_t 't) => x ret in
  let back'b = fun (ret : MutWrapper2_t 't) => y ret in
  Ok ((| x, y |), back'a, back'b)

(* [adt_borrows::{adt_borrows::MutWrapper2<'a, 'b, T>}::unwrap]:
   Source: 'tests/src/adt-borrows.rs', lines 139:4-141:5 *)
definition mutWrapper2_unwrap
  ('t) (self : MutWrapper2_t 't) :
  result (('t × 't) × ('t ⇒ MutWrapper2_t 't) × ('t ⇒ MutWrapper2_t 't))
  where
  let back'a = fun (ret : 't) => (| self with x := ret |) in
  let back'b = fun (ret : 't) => (| self with y := ret |) in
  Ok ((x self, y self), back'a, back'b)

(* [adt_borrows::{adt_borrows::MutWrapper2<'a, 'b, T>}::id]:
   Source: 'tests/src/adt-borrows.rs', lines 143:4-145:5 *)
definition mutWrapper2_id
  ('t) (self : MutWrapper2_t 't) :
  result ((MutWrapper2_t 't) × (MutWrapper2_t 't ⇒ MutWrapper2_t 't) ×
    (MutWrapper2_t 't ⇒ MutWrapper2_t 't))
  where
  let back'a = fun (ret : MutWrapper2_t 't) => (| self with x := x ret |) in
  let back'b = fun (ret : MutWrapper2_t 't) => (| self with y := y ret |) in
  Ok (self, back'a, back'b)

(* [adt_borrows::use_mut_wrapper2]:
   Source: 'tests/src/adt-borrows.rs', lines 148:0-157:1 *)
definition use_mut_wrapper2 : result unit where
  let (w, create_back, create_back1) = mutWrapper2_create 0 :: i32 10 :: i32 in
  let (p, unwrap_back, unwrap_back1) = mutWrapper2_unwrap w in
  let (px, py) = p in
  let px1 = i32_add px 1 :: i32 in
  let py1 = i32_add py 1 :: i32 in
  let x = create_back (| w with x := x (unwrap_back px1) |) in
  let _ = massert (x = 1 :: i32) in
  let y = create_back1 (| w with y := y (unwrap_back1 py1) |) in
  massert (y = 11 :: i32)

(* [adt_borrows::use_mut_wrapper2_id]:
   Source: 'tests/src/adt-borrows.rs', lines 159:0-161:1 *)
definition use_mut_wrapper2_id
  ('t) (x : MutWrapper2_t 't) :
  result ((MutWrapper2_t 't) × (MutWrapper2_t 't ⇒ MutWrapper2_t 't) ×
    (MutWrapper2_t 't ⇒ MutWrapper2_t 't))
  where
  let (mw, id_back, id_back1) = mutWrapper2_id x in
  let back'a =
    fun (ret : MutWrapper2_t 't) =>
      (| x with x := x (id_back (| mw with x := x ret |)) |)
  in
  let back'b =
    fun (ret : MutWrapper2_t 't) =>
      (| x with y := y (id_back1 (| mw with y := y ret |)) |)
  in
  Ok (mw, back'a, back'b)

(* [adt_borrows::array_shared_borrow]:
   Source: 'tests/src/adt-borrows.rs', lines 170:0-172:1 *)
definition array_shared_borrow
  (n : usize) (x : array u32 n) : result (array u32 n) where
  Ok x

(* [adt_borrows::array_mut_borrow]:
   Source: 'tests/src/adt-borrows.rs', lines 174:0-176:1 *)
definition array_mut_borrow
  (n : usize) (x : array u32 n) :
  result ((array u32 n) × (array u32 n ⇒ array u32 n))
  where
  Ok (x, fun (ret : array u32 n) => ret)

(* [adt_borrows::use_array_mut_borrow1]:
   Source: 'tests/src/adt-borrows.rs', lines 178:0-180:1 *)
definition use_array_mut_borrow1
  (n : usize) (x : array u32 n) :
  result ((array u32 n) × (array u32 n ⇒ array u32 n))
  where
  array_mut_borrow x

(* [adt_borrows::use_array_mut_borrow2]:
   Source: 'tests/src/adt-borrows.rs', lines 182:0-185:1 *)
definition use_array_mut_borrow2
  (n : usize) (x : array u32 n) :
  result ((array u32 n) × (array u32 n ⇒ array u32 n))
  where
  let (x1, array_mut_borrow_back) = array_mut_borrow x in
  let (a, array_mut_borrow_back1) = array_mut_borrow x1 in
  let back =
    fun (ret : array u32 n) =>
      let x2 = array_mut_borrow_back1 ret in array_mut_borrow_back x2
  in
  Ok (a, back)

(* [adt_borrows::boxed_slice_shared_borrow]:
   Source: 'tests/src/adt-borrows.rs', lines 187:0-189:1 *)
definition boxed_slice_shared_borrow (x : slice u32) : result (slice u32) where
  Ok x

(* [adt_borrows::boxed_slice_mut_borrow]:
   Source: 'tests/src/adt-borrows.rs', lines 191:0-193:1 *)
definition boxed_slice_mut_borrow
  (x : slice u32) : result ((slice u32) × (slice u32 ⇒ slice u32)) where
  Ok (x, fun (ret : slice u32) => ret)

(* [adt_borrows::use_boxed_slice_mut_borrow1]:
   Source: 'tests/src/adt-borrows.rs', lines 195:0-197:1 *)
definition use_boxed_slice_mut_borrow1
  (x : slice u32) : result ((slice u32) × (slice u32 ⇒ slice u32)) where
  boxed_slice_mut_borrow x

(* [adt_borrows::use_boxed_slice_mut_borrow2]:
   Source: 'tests/src/adt-borrows.rs', lines 199:0-202:1 *)
definition use_boxed_slice_mut_borrow2
  (x : slice u32) : result ((slice u32) × (slice u32 ⇒ slice u32)) where
  let (x1, boxed_slice_mut_borrow_back) = boxed_slice_mut_borrow x in
  let (s, boxed_slice_mut_borrow_back1) = boxed_slice_mut_borrow x1 in
  let back =
    fun (ret : slice u32) =>
      let s1 = boxed_slice_mut_borrow_back1 ret in
      boxed_slice_mut_borrow_back s1
  in
  Ok (s, back)
(* [adt_borrows::SharedList]
   Source: 'tests/src/adt-borrows.rs', lines 207:0-210:1 *)
datatype SharedList_t (''t') =
| SharedList_Nil SharedList_t 't
| SharedList_Cons 't of  SharedList_t 't ⇒ SharedList_t 't
(* [adt_borrows::{adt_borrows::SharedList<'a, T>}::push]:
   Source: 'tests/src/adt-borrows.rs', lines 214:4-216:5 *)
definition sharedList_push
  ('t) (self : SharedList_t 't) (x : 't) : result (SharedList_t 't) where
  Ok (SharedList_Cons x self)

(* [adt_borrows::{adt_borrows::SharedList<'a, T>}::pop]:
   Source: 'tests/src/adt-borrows.rs', lines 218:4-224:5 *)
definition sharedList_pop
  ('t) (self : SharedList_t 't) : result ('t × (SharedList_t 't)) where
  case self of
  | SharedList_Nil => Fail Failure
  | SharedList_Cons hd tl => Ok (hd, tl)
(* [adt_borrows::MutList]
   Source: 'tests/src/adt-borrows.rs', lines 227:0-230:1 *)
datatype MutList_t (''t') =
| MutList_Nil MutList_t 't
| MutList_Cons 't of  MutList_t 't ⇒ MutList_t 't
(* [adt_borrows::{adt_borrows::MutList<'a, T>}::push]:
   Source: 'tests/src/adt-borrows.rs', lines 234:4-236:5 *)
definition mutList_push
  ('t) (self : MutList_t 't) (x : 't) :
  result ((MutList_t 't) × (MutList_t 't ⇒ ((MutList_t 't) × 't)))
  where
  let back =
    fun (ret : MutList_t 't) =>
      let (x1, ml) =
        case ret of | MutList_Cons t ml1 => (t, ml1) | _ => (x, self)
      in
      (ml, x1)
  in
  Ok (MutList_Cons x self, back)

(* [adt_borrows::{adt_borrows::MutList<'a, T>}::pop]:
   Source: 'tests/src/adt-borrows.rs', lines 238:4-244:5 *)
definition mutList_pop
  ('t) (self : MutList_t 't) :
  result (('t × (MutList_t 't)) × (('t × (MutList_t 't)) ⇒ MutList_t 't))
  where
  case self of
  | MutList_Nil => Fail Failure
  | MutList_Cons hd tl =>
    let back =
      fun (ret : ('t × (MutList_t 't))) =>
        let (t, ml) = ret in MutList_Cons t ml
    in
    Ok ((hd, tl), back)

(* [adt_borrows::wrap_shared_in_option]:
   Source: 'tests/src/adt-borrows.rs', lines 247:0-249:1 *)
definition wrap_shared_in_option ('t) (x : 't) : result (option 't) where
  Ok (Some x)

(* [adt_borrows::wrap_mut_in_option]:
   Source: 'tests/src/adt-borrows.rs', lines 251:0-253:1 *)
definition wrap_mut_in_option
  ('t) (x : 't) : result ((option 't) × (option 't ⇒ 't)) where
  let back = fun (ret : option 't) => case ret of | Some t => t | _ => x in
  Ok (Some x, back)
(* [adt_borrows::List]
   Source: 'tests/src/adt-borrows.rs', lines 255:0-258:1 *)
datatype List_t (''t') =
| List_Cons 't of  List_t 't ⇒ List_t 't
| List_Nil List_t 't
where
  
  (* [adt_borrows::nth_shared]: loop 0:
     Source: 'tests/src/adt-borrows.rs', lines 261:4-270:1 *)
  fun nth_shared_loop
    ('t) (ls : List_t 't) (i : u32) : result (option 't) where
    case ls of
    | List_Cons x tl =>
      if i = 0 :: u32
      then Ok (Some x)
      else (let i1 = u32_sub i 1 :: u32 in nth_shared_loop tl i1)
    | List_Nil => Ok None
  
  (* [adt_borrows::nth_shared]:
     Source: 'tests/src/adt-borrows.rs', lines 260:0-270:1 *)
  definition nth_shared
    ('t) (ls : List_t 't) (i : u32) : result (option 't) where
    nth_shared_loop ls i
  
  where
    
    (* [adt_borrows::nth_mut]: loop 0:
       Source: 'tests/src/adt-borrows.rs', lines 273:4-282:1 *)
    fun nth_mut_loop
      ('t) (ls : List_t 't) (i : u32) :
      result ((option 't) × (option 't ⇒ List_t 't))
      where
      case ls of
      | List_Cons x tl =>
        if i = 0 :: u32
        then
          let back =
            fun (ret : option 't) =>
              let t = case ret of | Some t1 => t1 | _ => x in List_Cons t tl
          in
          Ok (Some x, back)
        else (
          let i1 = u32_sub i 1 :: u32 in
          let (o, back) = nth_mut_loop tl i1 in
          let back1 =
            fun (ret : option 't) => let tl1 = back ret in List_Cons x tl1
          in
          Ok (o, back1))
      | List_Nil =>
        let back = fun (ret : option 't) => List_Nil in Ok (None, back)
    
    (* [adt_borrows::nth_mut]:
       Source: 'tests/src/adt-borrows.rs', lines 272:0-282:1 *)
    definition nth_mut
      ('t) (ls : List_t 't) (i : u32) :
      result ((option 't) × (option 't ⇒ List_t 't))
      where
      nth_mut_loop ls i
    
    (* [adt_borrows::update_array_mut_borrow]:
       Source: 'tests/src/adt-borrows.rs', lines 284:0-286:1 *)
    definition update_array_mut_borrow
      (a : array u32 32 :: usize) :
      result ((array u32 32 :: usize) × (array u32 32 :: usize ⇒ array u32
        32 :: usize))
      where
      Ok (a, fun (ret : array u32 32 :: usize) => ret)
    
    where
      
      (* [adt_borrows::array_mut_borrow_loop1]: loop 0:
         Source: 'tests/src/adt-borrows.rs', lines 289:4-291:5 *)
      fun array_mut_borrow_loop1_loop
        (b : bool) (a : array u32 32 :: usize) :
        result (array u32 32 :: usize)
        where
        if b
        then (
          let (a1, update_array_mut_borrow_back) = update_array_mut_borrow a in
          let a2 = array_mut_borrow_loop1_loop True a1 in
          Ok (update_array_mut_borrow_back a2))
        else Ok a
      
      (* [adt_borrows::array_mut_borrow_loop1]:
         Source: 'tests/src/adt-borrows.rs', lines 288:0-292:1 *)
      definition array_mut_borrow_loop1
        (b : bool) (a : array u32 32 :: usize) :
        result (array u32 32 :: usize)
        where
        array_mut_borrow_loop1_loop b a
      
      where
        
        (* [adt_borrows::array_mut_borrow_loop2]: loop 0:
           Source: 'tests/src/adt-borrows.rs', lines 295:4-297:5 *)
        fun array_mut_borrow_loop2_loop
          (b : bool) (a : array u32 32 :: usize) :
          result ((array u32 32 :: usize) × (array u32 32 :: usize ⇒ array
            u32 32 :: usize))
          where
          if b
          then (
            let (a1, update_array_mut_borrow_back) = update_array_mut_borrow a
            in
            let (a2, back) = array_mut_borrow_loop2_loop True a1 in
            let back1 =
              fun (ret : array u32 32 :: usize) =>
                let a3 = back ret in update_array_mut_borrow_back a3
            in
            Ok (a2, back1))
          else Ok (a, fun (ret : array u32 32 :: usize) => ret)
        
        (* [adt_borrows::array_mut_borrow_loop2]:
           Source: 'tests/src/adt-borrows.rs', lines 294:0-299:1 *)
        definition array_mut_borrow_loop2
          (b : bool) (a : array u32 32 :: usize) :
          result ((array u32 32 :: usize) × (array u32 32 :: usize ⇒ array
            u32 32 :: usize))
          where
          array_mut_borrow_loop2_loop b a
        
        (* [adt_borrows::copy_shared_array]:
           Source: 'tests/src/adt-borrows.rs', lines 301:0-303:1 *)
        definition copy_shared_array
          (a : array u32 32 :: usize) : result (array u32 32 :: usize) where
          Ok a
        
        where
          
          (* [adt_borrows::array_shared_borrow_loop1]: loop 0:
             Source: 'tests/src/adt-borrows.rs', lines 306:4-308:5 *)
          fun array_shared_borrow_loop1_loop
            (b : bool) (a : array u32 32 :: usize) : result unit where
            if b
            then (
              let a1 = copy_shared_array a in
              array_shared_borrow_loop1_loop True a1)
            else Ok ()
          
          (* [adt_borrows::array_shared_borrow_loop1]:
             Source: 'tests/src/adt-borrows.rs', lines 305:0-309:1 *)
          definition array_shared_borrow_loop1
            (b : bool) (a : array u32 32 :: usize) : result unit where
            array_shared_borrow_loop1_loop b a
          
          where
            
            (* [adt_borrows::array_shared_borrow_loop2]: loop 0:
               Source: 'tests/src/adt-borrows.rs', lines 312:4-314:5 *)
            fun array_shared_borrow_loop2_loop
              (b : bool) (a : array u32 32 :: usize) :
              result (array u32 32 :: usize)
              where
              if b
              then (
                let a1 = copy_shared_array a in
                array_shared_borrow_loop2_loop True a1)
              else Ok a
            
            (* [adt_borrows::array_shared_borrow_loop2]:
               Source: 'tests/src/adt-borrows.rs', lines 311:0-316:1 *)
            definition array_shared_borrow_loop2
              (b : bool) (a : array u32 32 :: usize) :
              result (array u32 32 :: usize)
              where
              array_shared_borrow_loop2_loop b a
            
end
