(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [array_slice_index] *)

theory ArraySliceIndex
  imports
    Aeneas.Primitives
    begin
\m(* [core::ops::range::RangeFrom]
   Source: '/rustc/library/core/src/ops/range.rs', lines 189:0-189:25
   Name pattern: [core::ops::range::RangeFrom] *)
record core_ops_range_RangeFrom_t (''idx') = start : 'idx
(* Trait implementation: [core::slice::index::private_slice_index::{core::slice::index::private_slice_index::Sealed for core::ops::range::RangeFrom<usize>}]
   Source: '/rustc/library/core/src/slice/index.rs', lines 126:4-126:41
   Name pattern: [core::slice::index::private_slice_index::Sealed<core::ops::range::RangeFrom<usize>>] *)
definition
  core_slice_index_private_slice_index_SealedcoreopsrangeRangeFromUsize ::
  core_slice_index_private_slice_index_Sealed (core_ops_range_RangeFrom_t
  usize) = ()

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::get]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 546:4-546:45
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ slice 't ⇒ result (option (slice
         't))"

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::get_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 551:4-551:57
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_mut] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_mut ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ slice 't ⇒ result ((option
         (slice 't)) × (option (slice 't) ⇒ slice 't))"

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::get_unchecked]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 556:4-556:66
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_unchecked] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_unchecked
  ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ const_raw_ptr (slice 't) ⇒
         result (const_raw_ptr (slice 't))"

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::get_unchecked_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 562:4-562:66
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_unchecked_mut] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_unchecked_mut
  ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ mut_raw_ptr (slice 't) ⇒ result
         (mut_raw_ptr (slice 't))"

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::index]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 568:4-568:39
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::index] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_index ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ slice 't ⇒ result (slice 't)"

(* [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}::index_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 577:4-577:51
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::index_mut] *)
axiomatization
  core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_index_mut ::
  ('t) "core_ops_range_RangeFrom_t usize ⇒ slice 't ⇒ result ((slice 't) ×
         (slice 't ⇒ slice 't))"

(* Trait implementation: [core::slice::index::{core::slice::index::SliceIndex<@Slice<T>, @Slice<T>> for core::ops::range::RangeFrom<usize>}]
   Source: '/rustc/library/core/src/slice/index.rs', lines 542:0-542:62
   Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>] *)
definition core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice
  (''t') :: core_slice_index_SliceIndex (core_ops_range_RangeFrom_t usize)
  (slice 't) (slice 't)
  where "core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice = (|
  sealedInst =
    core_slice_index_private_slice_index_SealedcoreopsrangeRangeFromUsize
  get = core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get
  get_mut =
    core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_mut
  get_unchecked =
    core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_unchecked
  get_unchecked_mut =
    core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_get_unchecked_mut
  index = core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_index
  index_mut =
    core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice_index_mut
|)"

(* [array_slice_index::slice_use_index_range_from]:
   Source: 'tests/src/array_slice_index.rs', lines 5:0-7:1 *)
definition slice_use_index_range_from
  (s : slice u32) : result (slice u32) where
  core_slice_index_Slice_index
    (core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice u32) s
    (| start = 0 :: usize |)

(* [array_slice_index::slice_use_get_range_from]:
   Source: 'tests/src/array_slice_index.rs', lines 9:0-11:1 *)
definition slice_use_get_range_from
  (s : slice u32) : result (option (slice u32)) where
  core_slice_Slice_get
    (core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice u32) s
    (| start = 0 :: usize |)

(* [array_slice_index::slice_use_index_range]:
   Source: 'tests/src/array_slice_index.rs', lines 13:0-15:1 *)
definition slice_use_index_range (s : slice u32) : result (slice u32) where
  core_slice_index_Slice_index (core_slice_index_SliceIndexRangeUsizeSliceInst
    u32) s
    (|
      core_ops_range_Range_start = 0 :: usize,
      core_ops_range_Range_end_ = 1 :: usize
    |)

(* [array_slice_index::slice_use_get_range]:
   Source: 'tests/src/array_slice_index.rs', lines 17:0-19:1 *)
definition slice_use_get_range
  (s : slice u32) : result (option (slice u32)) where
  core_slice_Slice_get (core_slice_index_SliceIndexRangeUsizeSliceInst u32) s
    (|
      core_ops_range_Range_start = 0 :: usize,
      core_ops_range_Range_end_ = 1 :: usize
    |)

(* [array_slice_index::slice_use_index_mut_range_from]:
   Source: 'tests/src/array_slice_index.rs', lines 21:0-23:1 *)
definition slice_use_index_mut_range_from
  (s : slice u32) : result ((slice u32) × (slice u32 ⇒ slice u32)) where
  core_slice_index_Slice_index_mut
    (core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice u32) s
    (| start = 0 :: usize |)

(* [array_slice_index::slice_use_get_mut_range_from]:
   Source: 'tests/src/array_slice_index.rs', lines 25:0-27:1 *)
definition slice_use_get_mut_range_from
  (s : slice u32) :
  result ((option (slice u32)) × (option (slice u32) ⇒ slice u32))
  where
  core_slice_Slice_get_mut
    (core_slice_index_SliceIndexcoreopsrangeRangeFromUsizeSliceSlice u32) s
    (| start = 0 :: usize |)

end
