(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [arrays] *)

theory Arrays
  imports
    Aeneas.Primitives
    begin
\m(* [arrays::AB]
   Source: 'tests/src/arrays.rs', lines 7:0-10:1 *)
datatype AB_t = | AB_A AB_t | AB_B AB_t
(* [arrays::incr]:
   Source: 'tests/src/arrays.rs', lines 12:0-14:1 *)
definition incr (x : u32) : result u32 where
  u32_add x 1 :: u32

(* [arrays::array_to_shared_slice_]:
   Source: 'tests/src/arrays.rs', lines 20:0-22:1 *)
definition array_to_shared_slice_
  ('t) (s : array 't 32 :: usize) : result (slice 't) where
  Ok (array_to_slice s)

(* [arrays::array_to_mut_slice_]:
   Source: 'tests/src/arrays.rs', lines 25:0-27:1 *)
definition array_to_mut_slice_
  ('t) (s : array 't 32 :: usize) :
  result ((slice 't) × (slice 't ⇒ array 't 32 :: usize))
  where
  Ok (array_to_slice_mut s)

(* [arrays::array_len]:
   Source: 'tests/src/arrays.rs', lines 29:0-31:1 *)
definition array_len ('t) (s : array 't 32 :: usize) : result usize where
  let s1 = return(array_to_slice s) in Ok (slice_len s1)

(* [arrays::shared_array_len]:
   Source: 'tests/src/arrays.rs', lines 33:0-35:1 *)
definition shared_array_len
  ('t) (s : array 't 32 :: usize) : result usize where
  let s1 = return(array_to_slice s) in Ok (slice_len s1)

(* [arrays::shared_slice_len]:
   Source: 'tests/src/arrays.rs', lines 37:0-39:1 *)
definition shared_slice_len ('t) (s : slice 't) : result usize where
  Ok (slice_len s)

(* [arrays::index_array_shared]:
   Source: 'tests/src/arrays.rs', lines 41:0-43:1 *)
definition index_array_shared
  ('t) (s : array 't 32 :: usize) (i : usize) : result 't where
  array_index_usize s i

(* [arrays::index_array_u32]:
   Source: 'tests/src/arrays.rs', lines 48:0-50:1 *)
definition index_array_u32
  (s : array u32 32 :: usize) (i : usize) : result u32 where
  array_index_usize s i

(* [arrays::index_array_copy]:
   Source: 'tests/src/arrays.rs', lines 52:0-54:1 *)
definition index_array_copy (x : array u32 32 :: usize) : result u32 where
  array_index_usize x 0 :: usize

(* [arrays::index_mut_array]:
   Source: 'tests/src/arrays.rs', lines 56:0-58:1 *)
definition index_mut_array
  ('t) (s : array 't 32 :: usize) (i : usize) :
  result ('t × ('t ⇒ array 't 32 :: usize))
  where
  array_index_mut_usize s i

(* [arrays::index_slice]:
   Source: 'tests/src/arrays.rs', lines 60:0-62:1 *)
definition index_slice ('t) (s : slice 't) (i : usize) : result 't where
  slice_index_usize s i

(* [arrays::index_mut_slice]:
   Source: 'tests/src/arrays.rs', lines 64:0-66:1 *)
definition index_mut_slice
  ('t) (s : slice 't) (i : usize) : result ('t × ('t ⇒ slice 't)) where
  slice_index_mut_usize s i

(* [arrays::slice_subslice_shared_]:
   Source: 'tests/src/arrays.rs', lines 68:0-70:1 *)
definition slice_subslice_shared_
  (x : slice u32) (y : usize) (z : usize) : result (slice u32) where
  core_slice_index_Slice_index (core_slice_index_SliceIndexRangeUsizeSliceInst
    u32) x (| core_ops_range_Range_start = y, core_ops_range_Range_end_ = z |)

(* [arrays::slice_subslice_mut_]:
   Source: 'tests/src/arrays.rs', lines 72:0-74:1 *)
definition slice_subslice_mut_
  (x : slice u32) (y : usize) (z : usize) :
  result ((slice u32) × (slice u32 ⇒ slice u32))
  where
  core_slice_index_Slice_index_mut
    (core_slice_index_SliceIndexRangeUsizeSliceInst u32) x
    (| core_ops_range_Range_start = y, core_ops_range_Range_end_ = z |)

(* [arrays::array_to_slice_shared_]:
   Source: 'tests/src/arrays.rs', lines 76:0-78:1 *)
definition array_to_slice_shared_
  (x : array u32 32 :: usize) : result (slice u32) where
  Ok (array_to_slice x)

(* [arrays::array_to_slice_mut_]:
   Source: 'tests/src/arrays.rs', lines 80:0-82:1 *)
definition array_to_slice_mut_
  (x : array u32 32 :: usize) :
  result ((slice u32) × (slice u32 ⇒ array u32 32 :: usize))
  where
  Ok (array_to_slice_mut x)

(* [arrays::array_subslice_shared_]:
   Source: 'tests/src/arrays.rs', lines 84:0-86:1 *)
definition array_subslice_shared_
  (x : array u32 32 :: usize) (y : usize) (z : usize) :
  result (slice u32)
  where
  core_array_Array_index (core_ops_index_IndexSliceInst
    (core_slice_index_SliceIndexRangeUsizeSliceInst u32)) x
    (| core_ops_range_Range_start = y, core_ops_range_Range_end_ = z |)

(* [arrays::array_subslice_mut_]:
   Source: 'tests/src/arrays.rs', lines 88:0-90:1 *)
definition array_subslice_mut_
  (x : array u32 32 :: usize) (y : usize) (z : usize) :
  result ((slice u32) × (slice u32 ⇒ array u32 32 :: usize))
  where
  core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
    (core_slice_index_SliceIndexRangeUsizeSliceInst u32)) x
    (| core_ops_range_Range_start = y, core_ops_range_Range_end_ = z |)

(* [arrays::index_slice_0]:
   Source: 'tests/src/arrays.rs', lines 92:0-94:1 *)
definition index_slice_0 ('t) (s : slice 't) : result 't where
  slice_index_usize s 0 :: usize

(* [arrays::index_array_0]:
   Source: 'tests/src/arrays.rs', lines 96:0-98:1 *)
definition index_array_0 ('t) (s : array 't 32 :: usize) : result 't where
  array_index_usize s 0 :: usize

(* [arrays::index_index_array]:
   Source: 'tests/src/arrays.rs', lines 107:0-109:1 *)
definition index_index_array
  (s : array (array u32 32 :: usize) 32 :: usize) (i : usize) (j : usize) :
  result u32
  where
  let a = array_index_usize s i in array_index_usize a j

(* [arrays::update_update_array]:
   Source: 'tests/src/arrays.rs', lines 118:0-120:1 *)
definition update_update_array
  (s : array (array u32 32 :: usize) 32 :: usize) (i : usize) (j : usize) :
  result (array (array u32 32 :: usize) 32 :: usize)
  where
  let (a, index_mut_back) = array_index_mut_usize s i in
  let a1 = array_update_usize a j 0 :: u32 in
  Ok (index_mut_back a1)

(* [arrays::array_local_deep_copy]:
   Source: 'tests/src/arrays.rs', lines 122:0-124:1 *)
definition array_local_deep_copy
  (x : array u32 32 :: usize) : result unit where
  Ok ()

(* [arrays::array_update1]:
   Source: 'tests/src/arrays.rs', lines 127:0-129:1 *)
definition array_update1
  (a : slice u32) (i : usize) (x : u32) : result (slice u32) where
  let i1 = u32_add x 1 :: u32 in
  let i2 = usize_add i 1 :: usize in
  slice_update_usize a i2 i1

(* [arrays::array_update2]:
   Source: 'tests/src/arrays.rs', lines 132:0-135:1 *)
definition array_update2
  (a : slice u32) (i : usize) (x : u32) : result (slice u32) where
  let i1 = u32_add x 1 :: u32 in
  let a1 = slice_update_usize a i i1 in
  let i2 = usize_add i 1 :: usize in
  slice_update_usize a1 i2 i1

(* [arrays::array_update3]:
   Source: 'tests/src/arrays.rs', lines 137:0-141:1 *)
definition array_update3
  (a : slice u32) (i : usize) (x : u32) : result (slice u32) where
  let a1 = slice_update_usize a i x in
  let i1 = usize_add i 1 :: usize in
  let a2 = slice_update_usize a1 i1 x in
  let i2 = usize_add i 2 :: usize in
  slice_update_usize a2 i2 x

(* [arrays::take_array]:
   Source: 'tests/src/arrays.rs', lines 143:0-143:33 *)
definition take_array (a : array u32 2 :: usize) : result unit where
  Ok ()

(* [arrays::take_array_borrow]:
   Source: 'tests/src/arrays.rs', lines 144:0-144:41 *)
definition take_array_borrow (a : array u32 2 :: usize) : result unit where
  Ok ()

(* [arrays::take_slice]:
   Source: 'tests/src/arrays.rs', lines 145:0-145:31 *)
definition take_slice (s : slice u32) : result unit where
  Ok ()

(* [arrays::take_mut_slice]:
   Source: 'tests/src/arrays.rs', lines 146:0-146:39 *)
definition take_mut_slice (s : slice u32) : result (slice u32) where
  Ok s

(* [arrays::const_array]:
   Source: 'tests/src/arrays.rs', lines 148:0-150:1 *)
definition const_array : result (array u32 2 :: usize) where
  Ok (array_repeat 2 :: usize 0 :: u32)

(* [arrays::const_slice]:
   Source: 'tests/src/arrays.rs', lines 152:0-155:1 *)
definition const_slice : result u32 where
  let a = array_repeat 2 :: usize 0 :: u32 in
  let s = return(array_to_slice a) in
  slice_index_usize s 0 :: usize

(* [arrays::take_all]:
   Source: 'tests/src/arrays.rs', lines 163:0-175:1 *)
definition take_all : result unit where
  let x = array_repeat 2 :: usize 0 :: u32 in
  let _ = take_array x in
  let _ = take_array x in
  let _ = take_array_borrow x in
  let s = return(array_to_slice x) in
  let _ = take_slice s in
  let (s1, _) = return(array_to_slice_mut x) in
  let _ = take_mut_slice s1 in
  Ok ()

(* [arrays::index_array]:
   Source: 'tests/src/arrays.rs', lines 177:0-179:1 *)
definition index_array (x : array u32 2 :: usize) : result u32 where
  array_index_usize x 0 :: usize

(* [arrays::index_array_borrow]:
   Source: 'tests/src/arrays.rs', lines 180:0-182:1 *)
definition index_array_borrow (x : array u32 2 :: usize) : result u32 where
  array_index_usize x 0 :: usize

(* [arrays::index_slice_u32_0]:
   Source: 'tests/src/arrays.rs', lines 184:0-186:1 *)
definition index_slice_u32_0 (x : slice u32) : result u32 where
  slice_index_usize x 0 :: usize

(* [arrays::index_mut_slice_u32_0]:
   Source: 'tests/src/arrays.rs', lines 188:0-190:1 *)
definition index_mut_slice_u32_0
  (x : slice u32) : result (u32 × (slice u32)) where
  let i = slice_index_usize x 0 :: usize in Ok (i, x)

(* [arrays::index_all]:
   Source: 'tests/src/arrays.rs', lines 192:0-204:1 *)
definition index_all : result u32 where
  let x = array_repeat 2 :: usize 0 :: u32 in
  let i = index_array x in
  let i1 = u32_add i i in
  let i2 = index_array_borrow x in
  let i3 = u32_add i1 i2 in
  let s = return(array_to_slice x) in
  let i4 = index_slice_u32_0 s in
  let i5 = u32_add i3 i4 in
  let (s1, _) = return(array_to_slice_mut x) in
  let (i6, _) = index_mut_slice_u32_0 s1 in
  u32_add i5 i6

(* [arrays::update_array]:
   Source: 'tests/src/arrays.rs', lines 206:0-208:1 *)
definition update_array (x : array u32 2 :: usize) : result unit where
  let _ = array_index_mut_usize x 0 :: usize in Ok ()

(* [arrays::update_array_mut_borrow]:
   Source: 'tests/src/arrays.rs', lines 209:0-211:1 *)
definition update_array_mut_borrow
  (x : array u32 2 :: usize) : result (array u32 2 :: usize) where
  array_update_usize x 0 :: usize 1 :: u32

(* [arrays::update_mut_slice]:
   Source: 'tests/src/arrays.rs', lines 212:0-214:1 *)
definition update_mut_slice (x : slice u32) : result (slice u32) where
  slice_update_usize x 0 :: usize 1 :: u32

(* [arrays::update_all]:
   Source: 'tests/src/arrays.rs', lines 216:0-222:1 *)
definition update_all : result unit where
  let x = array_repeat 2 :: usize 0 :: u32 in
  let _ = update_array x in
  let _ = update_array x in
  let x1 = update_array_mut_borrow x in
  let (s, _) = return(array_to_slice_mut x1) in
  let _ = update_mut_slice s in
  Ok ()

(* [arrays::incr_array]:
   Source: 'tests/src/arrays.rs', lines 224:0-226:1 *)
definition incr_array
  (x : array u32 2 :: usize) : result (array u32 2 :: usize) where
  let i = array_index_usize x 0 :: usize in
  let i1 = u32_add i 1 :: u32 in
  array_update_usize x 0 :: usize i1

(* [arrays::incr_slice]:
   Source: 'tests/src/arrays.rs', lines 228:0-230:1 *)
definition incr_slice (x : slice u32) : result (slice u32) where
  let i = slice_index_usize x 0 :: usize in
  let i1 = u32_add i 1 :: u32 in
  slice_update_usize x 0 :: usize i1

(* [arrays::range_all]:
   Source: 'tests/src/arrays.rs', lines 235:0-239:1 *)
definition range_all : result unit where
  let x = array_repeat 4 :: usize 0 :: u32 in
  let (s, _) =
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u32)) x
      (|
        core_ops_range_Range_start = 1 :: usize,
        core_ops_range_Range_end_ = 3 :: usize
      |)
  in
  let _ = update_mut_slice s in
  Ok ()

(* [arrays::deref_array_borrow]:
   Source: 'tests/src/arrays.rs', lines 244:0-247:1 *)
definition deref_array_borrow (x : array u32 2 :: usize) : result u32 where
  array_index_usize x 0 :: usize

(* [arrays::deref_array_mut_borrow]:
   Source: 'tests/src/arrays.rs', lines 249:0-252:1 *)
definition deref_array_mut_borrow
  (x : array u32 2 :: usize) : result (u32 × (array u32 2 :: usize)) where
  let i = array_index_usize x 0 :: usize in Ok (i, x)

(* [arrays::take_array_t]:
   Source: 'tests/src/arrays.rs', lines 257:0-257:34 *)
definition take_array_t (a : array AB_t 2 :: usize) : result unit where
  Ok ()

(* [arrays::non_copyable_array]:
   Source: 'tests/src/arrays.rs', lines 259:0-267:1 *)
definition non_copyable_array : result unit where
  take_array_t (mk_array 2 :: usize [ AB_A, AB_B ])

where
  
  (* [arrays::sum]: loop 0:
     Source: 'tests/src/arrays.rs', lines 275:4-278:5 *)
  fun sum_loop (s : slice u32) (sum1 : u32) (i : usize) : result u32 where
    let i1 = slice_len s in
    if usize_lt i i1
    then (
      let i2 = slice_index_usize s i in
      let sum3 = u32_add sum1 i2 in
      let i3 = usize_add i 1 :: usize in
      sum_loop s sum3 i3)
    else Ok sum1
  
  (* [arrays::sum]:
     Source: 'tests/src/arrays.rs', lines 272:0-280:1 *)
  definition sum (s : slice u32) : result u32 where
    sum_loop s 0 :: u32 0 :: usize
  
  where
    
    (* [arrays::sum2]: loop 0:
       Source: 'tests/src/arrays.rs', lines 286:4-289:5 *)
    fun sum2_loop
      (s : slice u32) (s2 : slice u32) (sum1 : u32) (i : usize) :
      result u32
      where
      let i1 = slice_len s in
      if usize_lt i i1
      then (
        let i2 = slice_index_usize s i in
        let i3 = slice_index_usize s2 i in
        let i4 = u32_add i2 i3 in
        let sum3 = u32_add sum1 i4 in
        let i5 = usize_add i 1 :: usize in
        sum2_loop s s2 sum3 i5)
      else Ok sum1
    
    (* [arrays::sum2]:
       Source: 'tests/src/arrays.rs', lines 282:0-291:1 *)
    definition sum2 (s : slice u32) (s2 : slice u32) : result u32 where
      let i = slice_len s in
      let i1 = slice_len s2 in
      let _ = massert (i = i1) in
      sum2_loop s s2 0 :: u32 0 :: usize
    
    (* [arrays::f0]:
       Source: 'tests/src/arrays.rs', lines 293:0-296:1 *)
    definition f0 : result unit where
      let (s, _) =
        return(array_to_slice_mut (mk_array 2 :: usize [ 1 :: u32, 2 :: u32 ]))
      in
      let _ = slice_index_mut_usize s 0 :: usize in
      Ok ()
    
    (* [arrays::f1]:
       Source: 'tests/src/arrays.rs', lines 298:0-301:1 *)
    definition f1 : result unit where
      let _ =
        array_index_mut_usize (mk_array 2 :: usize [ 1 :: u32, 2 :: u32 ])
          0 :: usize
      in
      Ok ()
    
    (* [arrays::f2]:
       Source: 'tests/src/arrays.rs', lines 303:0-303:20 *)
    definition f2 (i : u32) : result unit where
      Ok ()
    
    (* [arrays::f4]:
       Source: 'tests/src/arrays.rs', lines 312:0-314:1 *)
    definition f4
      (x : array u32 32 :: usize) (y : usize) (z : usize) :
      result (slice u32)
      where
      core_array_Array_index (core_ops_index_IndexSliceInst
        (core_slice_index_SliceIndexRangeUsizeSliceInst u32)) x
        (| core_ops_range_Range_start = y, core_ops_range_Range_end_ = z |)
    
    (* [arrays::f3]:
       Source: 'tests/src/arrays.rs', lines 305:0-310:1 *)
    definition f3 : result u32 where
      let i =
        array_index_usize (mk_array 2 :: usize [ 1 :: u32, 2 :: u32 ])
          0 :: usize
      in
      let _ = f2 i in
      let b = array_repeat 32 :: usize 0 :: u32 in
      let s =
        return(array_to_slice (mk_array 2 :: usize [ 1 :: u32, 2 :: u32 ]))
      in
      let s1 = f4 b 16 :: usize 18 :: usize in
      sum2 s s1
    
    (* [arrays::SZ]
       Source: 'tests/src/arrays.rs', lines 316:0-316:25 *)
    definition sz_body :: result usize where "sz_body = Ok 32 :: usize"
    definition sz :: usize where "sz = get_result sz_body"
    
    (* [arrays::f5]:
       Source: 'tests/src/arrays.rs', lines 319:0-321:1 *)
    definition f5 (x : array u32 32 :: usize) : result u32 where
      array_index_usize x 0 :: usize
    
    (* [arrays::ite]:
       Source: 'tests/src/arrays.rs', lines 324:0-331:1 *)
    definition ite : result unit where
      let x = array_repeat 2 :: usize 0 :: u32 in
      let y = array_repeat 2 :: usize 0 :: u32 in
      let (s, _) = return(array_to_slice_mut x) in
      let _ = index_mut_slice_u32_0 s in
      let (s1, _) = return(array_to_slice_mut y) in
      let _ = index_mut_slice_u32_0 s1 in
      Ok ()
    
    where
      
      (* [arrays::zero_slice]: loop 0:
         Source: 'tests/src/arrays.rs', lines 336:4-339:5 *)
      fun zero_slice_loop
        (a : slice u8) (i : usize) (len : usize) : result (slice u8) where
        if usize_lt i len
        then (
          let a1 = slice_update_usize a i 0 :: u8 in
          let i1 = usize_add i 1 :: usize in
          zero_slice_loop a1 i1 len)
        else Ok a
      
      (* [arrays::zero_slice]:
         Source: 'tests/src/arrays.rs', lines 333:0-340:1 *)
      definition zero_slice (a : slice u8) : result (slice u8) where
        let len = slice_len a in zero_slice_loop a 0 :: usize len
      
      where
        
        (* [arrays::iter_mut_slice]: loop 0:
           Source: 'tests/src/arrays.rs', lines 345:4-347:5 *)
        fun iter_mut_slice_loop (len : usize) (i : usize) : result unit where
          if usize_lt i len
          then (let i1 = usize_add i 1 :: usize in iter_mut_slice_loop len i1)
          else Ok ()
        
        (* [arrays::iter_mut_slice]:
           Source: 'tests/src/arrays.rs', lines 342:0-348:1 *)
        definition iter_mut_slice (a : slice u8) : result (slice u8) where
          let len = slice_len a in
          let _ = iter_mut_slice_loop len 0 :: usize in
          Ok a
        
        where
          
          (* [arrays::sum_mut_slice]: loop 0:
             Source: 'tests/src/arrays.rs', lines 353:4-356:5 *)
          fun sum_mut_slice_loop
            (a : slice u32) (i : usize) (s : u32) : result u32 where
            let i1 = slice_len a in
            if usize_lt i i1
            then (
              let i2 = slice_index_usize a i in
              let s1 = u32_add s i2 in
              let i3 = usize_add i 1 :: usize in
              sum_mut_slice_loop a i3 s1)
            else Ok s
          
          (* [arrays::sum_mut_slice]:
             Source: 'tests/src/arrays.rs', lines 350:0-358:1 *)
          definition sum_mut_slice
            (a : slice u32) : result (u32 × (slice u32)) where
            let i = sum_mut_slice_loop a 0 :: usize 0 :: u32 in Ok (i, a)
          
          where
            
            (* [arrays::add_acc]: loop 0:
               Source: 'tests/src/arrays.rs', lines 362:4-371:5 *)
            fun add_acc_loop
              (pa_src : array u32 256 :: usize)
              (pe_dst : array u32 256 :: usize) (i : usize) :
              result ((array u32 256 :: usize) × (array u32 256 :: usize))
              where
              if usize_lt i 256 :: usize
              then (
                let a = array_index_usize pa_src i in
                let pa_src1 = array_update_usize pa_src i 0 :: u32 in
                let c = array_index_usize pe_dst i in
                let c1 = u32_add c a in
                let pe_dst1 = array_update_usize pe_dst i c1 in
                let i1 = usize_add i 1 :: usize in
                add_acc_loop pa_src1 pe_dst1 i1)
              else Ok (pa_src, pe_dst)
            
            (* [arrays::add_acc]:
               Source: 'tests/src/arrays.rs', lines 360:0-372:1 *)
            definition add_acc
              (pa_src : array u32 256 :: usize)
              (pe_dst : array u32 256 :: usize) :
              result ((array u32 256 :: usize) × (array u32 256 :: usize))
              where
              add_acc_loop pa_src pe_dst 0 :: usize
            
end
