(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [as_mut] *)

theory AsMut
  imports
    Aeneas.Primitives
    begin
\m
(* Trait declaration: [core::convert::AsMut]
   Source: '/rustc/library/core/src/convert/mod.rs', lines 370:0-370:46
   Name pattern: [core::convert::AsMut] *)
record core_convert_AsMut_t (''self') (''t') =
  as_mut :: 'self ⇒ result ('t × ('t ⇒ 'self))

(* [alloc::boxed::{core::convert::AsMut<T> for alloc::boxed::Box<T>}::as_mut]:
   Source: '/rustc/library/alloc/src/boxed.rs', lines 2053:4-2053:34
   Name pattern: [alloc::boxed::{core::convert::AsMut<Box<@T>, @T>}::as_mut] *)
axiomatization alloc_boxed_AsMutBoxT_as_mut ::
  ('t) (''a') "'t ⇒ result ('t × ('t ⇒ 't))"

(* Trait implementation: [alloc::boxed::{core::convert::AsMut<T> for alloc::boxed::Box<T>}]
   Source: '/rustc/library/alloc/src/boxed.rs', lines 2052:0-2052:52
   Name pattern: [core::convert::AsMut<Box<@T>, @T>] *)
definition core_convert_AsMutBoxT (''t') (''a') :: core_convert_AsMut_t 't 't
  where "core_convert_AsMutBoxT = (|
  as_mut = alloc_boxed_AsMutBoxT_as_mut 'a
|)"

(* [as_mut::use_box_as_mut]:
   Source: 'tests/src/as_mut.rs', lines 2:0-4:1 *)
definition use_box_as_mut ('t) (x : 't) : result ('t × ('t ⇒ 't)) where
  alloc_boxed_AsMutBoxT_as_mut alloc_alloc_Global x

(* [as_mut::use_as_mut]:
   Source: 'tests/src/as_mut.rs', lines 6:0-8:1 *)
definition use_as_mut
  ('s) ('t) ('coreconvertAsMutInst : core_convert_AsMut_t 't 's') (x : 't) :
  result ('s × ('s ⇒ 't))
  where
  coreconvertAsMutInst.as_mut x

end
