(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [bitwise] *)

theory Bitwise
  imports
    Aeneas.Primitives
    begin
\m
(* [bitwise::shift_u32]:
   Source: 'tests/src/bitwise.rs', lines 5:0-10:1 *)
definition shift_u32 (a : u32) : result u32 where
  let t = u32_shr a 16 :: usize in u32_shl t 16 :: usize

(* [bitwise::shift_i32]:
   Source: 'tests/src/bitwise.rs', lines 12:0-17:1 *)
definition shift_i32 (a : i32) : result i32 where
  let t = i32_shr a 16 :: isize in i32_shl t 16 :: isize

(* [bitwise::xor_u32]:
   Source: 'tests/src/bitwise.rs', lines 19:0-21:1 *)
definition xor_u32 (a : u32) (b : u32) : result u32 where
  Ok (u32_xor a b)

(* [bitwise::or_u32]:
   Source: 'tests/src/bitwise.rs', lines 23:0-25:1 *)
definition or_u32 (a : u32) (b : u32) : result u32 where
  Ok (u32_or a b)

(* [bitwise::and_u32]:
   Source: 'tests/src/bitwise.rs', lines 27:0-29:1 *)
definition and_u32 (a : u32) (b : u32) : result u32 where
  Ok (u32_and a b)

end
