(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [blanket_impl] *)

theory BlanketImpl
  imports
    Aeneas.Primitives
    begin
\m
(* Trait declaration: [blanket_impl::Trait1]
   Source: 'tests/src/blanket_impl.rs', lines 3:0-3:15 *)
record Trait1_t (''self') = unit

(* Trait declaration: [blanket_impl::Trait2]
   Source: 'tests/src/blanket_impl.rs', lines 4:0-6:1 *)
record Trait2_t (''self') = foo :: result unit

(* [blanket_impl::Trait2::foo]:
   Source: 'tests/src/blanket_impl.rs', lines 5:4-5:15 *)
definition trait2_foo_default (''self') : result unit where
  Ok ()

(* [blanket_impl::{blanket_impl::Trait2 for T}::foo]:
   Source: 'tests/src/blanket_impl.rs', lines 9:0-9:31 *)
definition trait2_Blanket_foo
  ('t) ('trait1Inst : Trait1_t 't') : result unit where
  Ok ()

(* Trait implementation: [blanket_impl::{blanket_impl::Trait2 for T}]
   Source: 'tests/src/blanket_impl.rs', lines 9:0-9:31 *)
definition trait2_Blanket ('t) ('trait1Inst : Trait1_t 't') :: Trait2_t 't
  where "trait2_Blanket = (|
  foo = trait2_Blanket_foo trait1Inst
|)"

end
