(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [builtin] *)

theory Builtin
  imports
    Aeneas.Primitives
    begin
\m
(* Trait declaration: [core::convert::Into]
   Source: '/rustc/library/core/src/convert/mod.rs', lines 450:0-450:24
   Name pattern: [core::convert::Into] *)
record core_convert_Into_t (''self') (''t') = into :: 'self ⇒ result 't

(* [core::convert::{core::convert::Into<U> for T}::into]:
   Source: '/rustc/library/core/src/convert/mod.rs', lines 776:4-776:22
   Name pattern: [core::convert::{core::convert::Into<@T, @U>}::into] *)
axiomatization core_convert_Into_Blanket_into ::
  ('t) ('u) ('fromInst : core_convert_From 'u 't') "'t ⇒ result 'u"

(* Trait implementation: [core::convert::{core::convert::Into<U> for T}]
   Source: '/rustc/library/core/src/convert/mod.rs', lines 766:0-768:22
   Name pattern: [core::convert::Into<@T, @U>] *)
definition core_convert_Into_Blanket ('t) ('u) ('fromInst : core_convert_From
  'u 't') :: core_convert_Into_t 't 'u where "core_convert_Into_Blanket = (|
  into = core_convert_Into_Blanket_into fromInst
|)"

(* [core::convert::{core::convert::From<T> for T}::from]:
   Source: '/rustc/library/core/src/convert/mod.rs', lines 787:4-787:22
   Name pattern: [core::convert::{core::convert::From<@T, @T>}::from] *)
axiomatization core_convert_From_Blanket_from :: ('t) "'t ⇒ result 't"

(* Trait implementation: [core::convert::{core::convert::From<T> for T}]
   Source: '/rustc/library/core/src/convert/mod.rs', lines 784:0-784:27
   Name pattern: [core::convert::From<@T, @T>] *)
definition core_convert_From_Blanket (''t') :: core_convert_From 't 't
  where "core_convert_From_Blanket = (|
  from_ = core_convert_From_Blanket_from
|)"

(* Trait declaration: [core::fmt::Debug]
   Source: '/rustc/library/core/src/fmt/mod.rs', lines 873:0-873:29
   Name pattern: [core::fmt::Debug] *)
record core_fmt_Debug_t (''self') = unit

(* [builtin::clone_bool]:
   Source: 'tests/src/builtin.rs', lines 6:0-8:1 *)
definition clone_bool (x : bool) : result bool where
  Ok (core_clone_impls_CloneBool_clone x)

(* [builtin::clone_u32]:
   Source: 'tests/src/builtin.rs', lines 10:0-12:1 *)
definition clone_u32 (x : u32) : result u32 where
  Ok (core_clone_impls_CloneU32_clone x)

(* [builtin::into_from]:
   Source: 'tests/src/builtin.rs', lines 14:0-16:1 *)
definition into_from
  ('t) ('u) ('coreconvertFromInst : core_convert_From 'u 't') (x : 't) :
  result 'u
  where
  core_convert_Into_Blanket_into coreconvertFromInst x

(* [builtin::into_same]:
   Source: 'tests/src/builtin.rs', lines 18:0-20:1 *)
definition into_same ('t) (x : 't) : result 't where
  core_convert_Into_Blanket_into (core_convert_From_Blanket 't) x

(* [builtin::from_same]:
   Source: 'tests/src/builtin.rs', lines 22:0-24:1 *)
definition from_same ('t) (x : 't) : result 't where
  core_convert_From_Blanket_from x

(* [builtin::copy]:
   Source: 'tests/src/builtin.rs', lines 26:0-28:1 *)
definition copy
  ('t) ('coremarkerCopyInst : core_marker_Copy 't') (x : 't) : result 't where
  Ok x

(* [builtin::u32_from_le_bytes]:
   Source: 'tests/src/builtin.rs', lines 30:0-32:1 *)
definition u32_from_le_bytes (x : array u8 4 :: usize) : result u32 where
  Ok (core_num_U32_from_le_bytes x)

(* [builtin::u32_to_le_bytes]:
   Source: 'tests/src/builtin.rs', lines 34:0-36:1 *)
definition u32_to_le_bytes (x : u32) : result (array u8 4 :: usize) where
  Ok (core_num_U32_to_le_bytes x)

(* [builtin::use_debug_clause]:
   Source: 'tests/src/builtin.rs', lines 38:0-38:49 *)
definition use_debug_clause
  ('t) ('corefmtDebugInst : core_fmt_Debug_t 't') (t : 't) : result unit where
  Ok ()

end
