(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [defaulted_method] *)

theory DefaultedMethod
  imports
    Aeneas.Primitives
    begin
\m
(* Trait declaration: [core::cmp::PartialEq]
   Source: '/rustc/library/core/src/cmp.rs', lines 252:0-252:59
   Name pattern: [core::cmp::PartialEq] *)
record core_cmp_PartialEq_t (''self') (''rhs') =
  eq :: 'self ⇒ 'rhs ⇒ result bool

(* Trait declaration: [core::cmp::Eq]
   Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:44
   Name pattern: [core::cmp::Eq] *)
record core_cmp_Eq_t (''self') =
  partialEqInst :: core_cmp_PartialEq_t 'self 'self
(* [core::cmp::Ordering]
   Source: '/rustc/library/core/src/cmp.rs', lines 392:0-392:17
   Name pattern: [core::cmp::Ordering] *)
datatype core_cmp_Ordering_t =
| Core_cmp_Ordering_Less core_cmp_Ordering_t
| Core_cmp_Ordering_Equal core_cmp_Ordering_t
| Core_cmp_Ordering_Greater core_cmp_Ordering_t
(* Trait declaration: [core::cmp::PartialOrd]
   Source: '/rustc/library/core/src/cmp.rs', lines 1345:0-1345:77
   Name pattern: [core::cmp::PartialOrd] *)
record core_cmp_PartialOrd_t (''self') (''rhs') =
  partialEqInst :: core_cmp_PartialEq_t 'self 'rhs
  partial_cmp :: 'self ⇒ 'rhs ⇒ result (option core_cmp_Ordering_t)

(* Trait declaration: [core::cmp::Ord]
   Source: '/rustc/library/core/src/cmp.rs', lines 961:0-961:51
   Name pattern: [core::cmp::Ord] *)
record core_cmp_Ord_t (''self') =
  eqInst :: core_cmp_Eq_t 'self
  partialOrdInst :: core_cmp_PartialOrd_t 'self 'self
  cmp :: 'self ⇒ 'self ⇒ result core_cmp_Ordering_t
  min :: 'self ⇒ 'self ⇒ result 'self

(* [core::cmp::Ord::min]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1052:4-1054:20
   Name pattern: [core::cmp::Ord::min] *)
axiomatization core_cmp_Ord_min_default ::
  ('self) ('ordInst : core_cmp_Ord_t 'self') "'self ⇒ 'self ⇒ result 'self"

(* [core::cmp::impls::{core::cmp::PartialEq<i32> for i32}::eq]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1816:16-1816:50
   Name pattern: [core::cmp::impls::{core::cmp::PartialEq<i32, i32>}::eq] *)
axiomatization core_cmp_impls_PartialEqI32I32_eq ::
  "i32 ⇒ i32 ⇒ result bool"

(* [core::cmp::impls::{core::cmp::PartialOrd<i32> for i32}::partial_cmp]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1931:16-1931:71
   Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<i32, i32>}::partial_cmp] *)
axiomatization core_cmp_impls_PartialOrdI32I32_partial_cmp ::
  "i32 ⇒ i32 ⇒ result (option core_cmp_Ordering_t)"

(* [core::cmp::impls::{core::cmp::Ord for i32}::cmp]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1941:16-1941:55
   Name pattern: [core::cmp::impls::{core::cmp::Ord<i32>}::cmp] *)
axiomatization core_cmp_impls_OrdI32_cmp ::
  "i32 ⇒ i32 ⇒ result core_cmp_Ordering_t"

(* [core::cmp::impls::{core::cmp::Ord for i32}::min]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1939:12-1939:27
   Name pattern: [core::cmp::impls::{core::cmp::Ord<i32>}::min] *)
axiomatization core_cmp_impls_OrdI32_min :: "i32 ⇒ i32 ⇒ result i32"

(* Trait declaration: [defaulted_method::Trait]
   Source: 'tests/src/defaulted_method.rs', lines 2:0-7:1 *)
record Trait_t (''self') =
  provided_method :: 'self ⇒ result u32
  required_method :: 'self ⇒ result u32

(* [defaulted_method::Trait::provided_method]:
   Source: 'tests/src/defaulted_method.rs', lines 3:4-5:5 *)
definition trait_provided_method_default
  ('self) ('traitInst : Trait_t 'self') (self : 'self) : result u32 where
  traitInst.required_method self
(* [defaulted_method::NoOverride]
   Source: 'tests/src/defaulted_method.rs', lines 9:0-9:18 *)
record NoOverride_t = 

(* [defaulted_method::{defaulted_method::Trait for defaulted_method::NoOverride}::provided_method]:
   Source: 'tests/src/defaulted_method.rs', lines 11:4-13:5 *)
definition traitdefaulted_methodNoOverride_provided_method
  (self : NoOverride_t) : result u32 where
  Ok 73 :: u32

(* [defaulted_method::{defaulted_method::Trait for defaulted_method::NoOverride}::required_method]:
   Source: 'tests/src/defaulted_method.rs', lines 14:4-16:5 *)
definition traitdefaulted_methodNoOverride_required_method
  (self : NoOverride_t) : result u32 where
  Ok 12 :: u32

(* Trait implementation: [defaulted_method::{defaulted_method::Trait for defaulted_method::NoOverride}]
   Source: 'tests/src/defaulted_method.rs', lines 10:0-17:1 *)
definition traitdefaulted_methodNoOverride :: Trait_t NoOverride_t
  where "traitdefaulted_methodNoOverride = (|
  provided_method = traitdefaulted_methodNoOverride_provided_method
  required_method = traitdefaulted_methodNoOverride_required_method
|)"
(* [defaulted_method::YesOverride]
   Source: 'tests/src/defaulted_method.rs', lines 19:0-19:19 *)
record YesOverride_t = 

(* [defaulted_method::{defaulted_method::Trait for defaulted_method::YesOverride}::required_method]:
   Source: 'tests/src/defaulted_method.rs', lines 21:4-23:5 *)
definition traitdefaulted_methodYesOverride_required_method
  (self : YesOverride_t) : result u32 where
  Ok 42 :: u32

(* [defaulted_method::{defaulted_method::Trait for defaulted_method::YesOverride}::provided_method]:
   Source: 'tests/src/defaulted_method.rs', lines 20:0-24:1 *)
definition traitdefaulted_methodYesOverride_provided_method
  (self : YesOverride_t) : result u32 where
  traitdefaulted_methodYesOverride_required_method self

(* Trait implementation: [defaulted_method::{defaulted_method::Trait for defaulted_method::YesOverride}]
   Source: 'tests/src/defaulted_method.rs', lines 20:0-24:1 *)
definition traitdefaulted_methodYesOverride :: Trait_t YesOverride_t
  where "traitdefaulted_methodYesOverride = (|
  provided_method = traitdefaulted_methodYesOverride_provided_method
  required_method = traitdefaulted_methodYesOverride_required_method
|)"

(* [defaulted_method::main]:
   Source: 'tests/src/defaulted_method.rs', lines 26:0-33:1 *)
definition main : result unit where
  let _ = traitdefaulted_methodNoOverride_provided_method () in
  let _ = traitdefaulted_methodYesOverride_provided_method () in
  let n = core_cmp_impls_OrdI32_min 10 :: i32 1 :: i32 in
  massert (n = 1 :: i32)

end
