(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [deref] *)

theory Deref
  imports
    Aeneas.Primitives
    begin
\m
(* [deref::use_deref_box]:
   Source: 'tests/src/deref.rs', lines 6:0-8:1 *)
definition use_deref_box ('t) (x : 't) : result 't where
  Ok (alloc_boxed_Box_deref x)

(* [deref::use_deref_mut_box]:
   Source: 'tests/src/deref.rs', lines 10:0-12:1 *)
definition use_deref_mut_box ('t) (x : 't) : result ('t × ('t ⇒ 't)) where
  Ok (alloc_boxed_Box_deref_mut x)

(* [deref::test_deref_box]:
   Source: 'tests/src/deref.rs', lines 14:0-22:1 *)
definition test_deref_box : result unit where
  let (_, deref_mut_back) = return(alloc_boxed_Box_deref_mut 0 :: i32) in
  let b = deref_mut_back 1 :: i32 in
  let x = return(alloc_boxed_Box_deref b) in
  massert (x = 1 :: i32)

(* [deref::use_deref_vec]:
   Source: 'tests/src/deref.rs', lines 24:0-26:1 *)
definition use_deref_vec ('t) (x : alloc_vec_Vec 't) : result (slice 't) where
  Ok (alloc_vec_Vec_deref x)

(* [deref::use_deref_mut_vec]:
   Source: 'tests/src/deref.rs', lines 28:0-30:1 *)
definition use_deref_mut_vec
  ('t) (x : alloc_vec_Vec 't) :
  result ((slice 't) × (slice 't ⇒ alloc_vec_Vec 't))
  where
  Ok (alloc_vec_Vec_deref_mut x)

end
