(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [dynamic_size] *)

theory DynamicSize
  imports
    Aeneas.Primitives
    begin
\m
(* [dynamic_size::alloc_slice]:
   Source: 'tests/src/dynamic_size.rs', lines 3:0-5:1 *)
definition alloc_slice ('n : usize') : result (slice u8) where
  let a = array_repeat n 0 :: u8 in Ok (array_to_slice a)
(* [dynamic_size::Wrapper]
   Source: 'tests/src/dynamic_size.rs', lines 7:0-9:1 *)
record Wrapper_t (''t') = data : 't
(* [dynamic_size::alloc_wrapper]:
   Source: 'tests/src/dynamic_size.rs', lines 11:0-13:1 *)
definition alloc_wrapper ('n : usize') : result (Wrapper_t (slice u8)) where
  let a = array_repeat n 0 :: u8 in
  let w = (| data = a |) in
  Ok (| w with data := (array_to_slice data w) |)

end
