(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [infinite_loop] *)

theory InfiniteLoop
  imports
    Aeneas.Primitives
    begin
\m
(* [infinite_loop::bar]:
   Source: 'tests/src/infinite-loop.rs', lines 4:0-4:11 *)
definition bar : result unit where
  Ok ()

where
  
  (* [infinite_loop::foo]: loop 0:
     Source: 'tests/src/infinite-loop.rs', lines 8:8-8:13 *)
  fun foo_loop : result unit where
    let _ = bar in foo_loop
  
  (* [infinite_loop::foo]:
     Source: 'tests/src/infinite-loop.rs', lines 6:0-10:1 *)
  definition foo : result unit where
    foo_loop
  
end
