(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [issue_440_type_error] *)

theory Issue440TypeError
  imports
    Aeneas.Primitives
    begin
\m(* [issue_440_type_error::PeanoNum]
   Source: 'tests/src/issue-440-type-error.rs', lines 3:0-6:1 *)
datatype PeanoNum_t =
| PeanoNum_Zero PeanoNum_t
| PeanoNum_Succ PeanoNum_t ⇒ PeanoNum_t
(* [issue_440_type_error::f]:
   Source: 'tests/src/issue-440-type-error.rs', lines 8:0-15:1 *)
definition f (x : PeanoNum_t) (value1 : isize) : result PeanoNum_t where
  case x of
  | PeanoNum_Zero =>
    let (_, x1) = core_mem_replace PeanoNum_Zero (PeanoNum_Succ PeanoNum_Zero)
    in
    Ok x1
  | PeanoNum_Succ _ => Ok x

end
