(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [issue_270_loop_list] *)

theory Issue270LoopList
  imports
    Aeneas.Primitives
    begin
\m(* [issue_270_loop_list::List]
   Source: 'tests/src/issue-270-loop-list.rs', lines 2:0-5:1 *)
datatype List_t (''t') =
| List_Cons 't of  List_t 't ⇒ List_t 't
| List_Nil List_t 't
where
  
  (* [issue_270_loop_list::foo]: loop 0:
     Source: 'tests/src/issue-270-loop-list.rs', lines 10:8-12:9 *)
  fun foo_loop (t : List_t (List_t u8)) : result unit where
    case t of | List_Cons _ tt => foo_loop tt | List_Nil => Ok ()
  
  (* [issue_270_loop_list::foo]:
     Source: 'tests/src/issue-270-loop-list.rs', lines 7:0-14:1 *)
  definition foo (v : List_t (List_t u8)) : result unit where
    case v of | List_Cons l t => foo_loop t | List_Nil => Ok ()
  
end
