(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [loops] *)

theory Loops
  imports
    Aeneas.Primitives
    begin
\m
where
  
  (* [loops::sum]: loop 0:
     Source: 'tests/src/loops.rs', lines 11:4-14:5 *)
  fun sum_loop (max : u32) (i : u32) (s : u32) : result u32 where
    if u32_lt i max
    then (
      let s1 = u32_add s i in let i1 = u32_add i 1 :: u32 in sum_loop max i1 s1)
    else u32_mul s 2 :: u32
  
  (* [loops::sum]:
     Source: 'tests/src/loops.rs', lines 8:0-18:1 *)
  definition sum (max : u32) : result u32 where
    sum_loop max 0 :: u32 0 :: u32
  
  where
    
    (* [loops::sum_with_mut_borrows]: loop 0:
       Source: 'tests/src/loops.rs', lines 26:4-31:5 *)
    fun sum_with_mut_borrows_loop
      (max : u32) (i : u32) (s : u32) : result u32 where
      if u32_lt i max
      then (
        let ms = u32_add s i in
        let mi = u32_add i 1 :: u32 in
        sum_with_mut_borrows_loop max mi ms)
      else u32_mul s 2 :: u32
    
    (* [loops::sum_with_mut_borrows]:
       Source: 'tests/src/loops.rs', lines 23:0-35:1 *)
    definition sum_with_mut_borrows (max : u32) : result u32 where
      sum_with_mut_borrows_loop max 0 :: u32 0 :: u32
    
    where
      
      (* [loops::sum_with_shared_borrows]: loop 0:
         Source: 'tests/src/loops.rs', lines 41:4-48:5 *)
      fun sum_with_shared_borrows_loop
        (max : u32) (i : u32) (s : u32) : result u32 where
        if u32_lt i max
        then (
          let i1 = u32_add i 1 :: u32 in
          let s1 = u32_add s i1 in
          sum_with_shared_borrows_loop max i1 s1)
        else u32_mul s 2 :: u32
      
      (* [loops::sum_with_shared_borrows]:
         Source: 'tests/src/loops.rs', lines 38:0-52:1 *)
      definition sum_with_shared_borrows (max : u32) : result u32 where
        sum_with_shared_borrows_loop max 0 :: u32 0 :: u32
      
      where
        
        (* [loops::sum_array]: loop 0:
           Source: 'tests/src/loops.rs', lines 57:4-60:5 *)
        fun sum_array_loop
          (n : usize) (a : array u32 n) (i : usize) (s : u32) :
          result u32
          where
          if usize_lt i n
          then (
            let i1 = array_index_usize a i in
            let s1 = u32_add s i1 in
            let i2 = usize_add i 1 :: usize in
            sum_array_loop a i2 s1)
          else Ok s
        
        (* [loops::sum_array]:
           Source: 'tests/src/loops.rs', lines 54:0-62:1 *)
        definition sum_array (n : usize) (a : array u32 n) : result u32 where
          sum_array_loop a 0 :: usize 0 :: u32
        
        where
          
          (* [loops::clear]: loop 0:
             Source: 'tests/src/loops.rs', lines 68:4-71:5 *)
          fun clear_loop
            (v : alloc_vec_Vec u32) (i : usize) :
            result (alloc_vec_Vec u32)
            where
            let i1 = alloc_vec_Vec_len v in
            if usize_lt i i1
            then (
              let (_, index_mut_back) =
                alloc_vec_Vec_index_mut
                  (core_slice_index_SliceIndexUsizeSliceInst u32) v i
              in
              let i2 = usize_add i 1 :: usize in
              let v1 = index_mut_back 0 :: u32 in
              clear_loop v1 i2)
            else Ok v
          
          (* [loops::clear]:
             Source: 'tests/src/loops.rs', lines 66:0-72:1 *)
          definition clear
            (v : alloc_vec_Vec u32) : result (alloc_vec_Vec u32) where
            clear_loop v 0 :: usize
          (* [loops::List]
             Source: 'tests/src/loops.rs', lines 74:0-77:1 *)
          datatype List_t (''t') =
          | List_Cons 't of  List_t 't ⇒ List_t 't
          | List_Nil List_t 't
          where
            
            (* [loops::list_mem]: loop 0:
               Source: 'tests/src/loops.rs', lines 81:4-89:1 *)
            fun list_mem_loop (x : u32) (ls : List_t u32) : result bool where
              case ls of
              | List_Cons y tl => if y = x then Ok True else list_mem_loop x tl
              | List_Nil => Ok False
            
            (* [loops::list_mem]:
               Source: 'tests/src/loops.rs', lines 80:0-89:1 *)
            definition list_mem (x : u32) (ls : List_t u32) : result bool where
              list_mem_loop x ls
            
            where
              
              (* [loops::list_nth_mut_loop]: loop 0:
                 Source: 'tests/src/loops.rs', lines 93:4-102:1 *)
              fun list_nth_mut_loop_loop
                ('t) (ls : List_t 't) (i : u32) :
                result ('t × ('t ⇒ List_t 't))
                where
                case ls of
                | List_Cons x tl =>
                  if i = 0 :: u32
                  then
                    let back = fun (ret : 't) => List_Cons ret tl in
                    Ok (x, back)
                  else (
                    let i1 = u32_sub i 1 :: u32 in
                    let (t, back) = list_nth_mut_loop_loop tl i1 in
                    let back1 =
                      fun (ret : 't) => let tl1 = back ret in List_Cons x tl1
                    in
                    Ok (t, back1))
                | List_Nil => Fail Failure
              
              (* [loops::list_nth_mut_loop]:
                 Source: 'tests/src/loops.rs', lines 92:0-102:1 *)
              definition list_nth_mut_loop
                ('t) (ls : List_t 't) (i : u32) :
                result ('t × ('t ⇒ List_t 't))
                where
                list_nth_mut_loop_loop ls i
              
              where
                
                (* [loops::list_nth_shared_loop]: loop 0:
                   Source: 'tests/src/loops.rs', lines 106:4-115:1 *)
                fun list_nth_shared_loop_loop
                  ('t) (ls : List_t 't) (i : u32) : result 't where
                  case ls of
                  | List_Cons x tl =>
                    if i = 0 :: u32
                    then Ok x
                    else (
                      let i1 = u32_sub i 1 :: u32 in
                      list_nth_shared_loop_loop tl i1)
                  | List_Nil => Fail Failure
                
                (* [loops::list_nth_shared_loop]:
                   Source: 'tests/src/loops.rs', lines 105:0-115:1 *)
                definition list_nth_shared_loop
                  ('t) (ls : List_t 't) (i : u32) : result 't where
                  list_nth_shared_loop_loop ls i
                
                where
                  
                  (* [loops::get_elem_mut]: loop 0:
                     Source: 'tests/src/loops.rs', lines 119:4-131:1 *)
                  fun get_elem_mut_loop
                    (x : usize) (ls : List_t usize) :
                    result (usize × (usize ⇒ List_t usize))
                    where
                    case ls of
                    | List_Cons y tl =>
                      if y = x
                      then
                        let back = fun (ret : usize) => List_Cons ret tl in
                        Ok (y, back)
                      else (
                        let (i, back) = get_elem_mut_loop x tl in
                        let back1 =
                          fun (ret : usize) =>
                            let tl1 = back ret in List_Cons y tl1
                        in
                        Ok (i, back1))
                    | List_Nil => Fail Failure
                  
                  (* [loops::get_elem_mut]:
                     Source: 'tests/src/loops.rs', lines 117:0-131:1 *)
                  definition get_elem_mut
                    (slots : alloc_vec_Vec (List_t usize)) (x : usize) :
                    result (usize × (usize ⇒ alloc_vec_Vec (List_t usize)))
                    where
                    let (ls, index_mut_back) =
                      alloc_vec_Vec_index_mut
                        (core_slice_index_SliceIndexUsizeSliceInst (List_t
                        usize)) slots 0 :: usize
                    in
                    let (i, back) = get_elem_mut_loop x ls in
                    let back1 =
                      fun (ret : usize) => let l = back ret in index_mut_back l
                    in
                    Ok (i, back1)
                  
                  where
                    
                    (* [loops::get_elem_shared]: loop 0:
                       Source: 'tests/src/loops.rs', lines 135:4-147:1 *)
                    fun get_elem_shared_loop
                      (x : usize) (ls : List_t usize) : result usize where
                      case ls of
                      | List_Cons y tl =>
                        if y = x then Ok y else get_elem_shared_loop x tl
                      | List_Nil => Fail Failure
                    
                    (* [loops::get_elem_shared]:
                       Source: 'tests/src/loops.rs', lines 133:0-147:1 *)
                    definition get_elem_shared
                      (slots : alloc_vec_Vec (List_t usize)) (x : usize) :
                      result usize
                      where
                      let ls =
                        alloc_vec_Vec_index
                          (core_slice_index_SliceIndexUsizeSliceInst (List_t
                          usize)) slots 0 :: usize
                      in
                      get_elem_shared_loop x ls
                    
                    (* [loops::id_mut]:
                       Source: 'tests/src/loops.rs', lines 149:0-151:1 *)
                    definition id_mut
                      ('t) (ls : List_t 't) :
                      result ((List_t 't) × (List_t 't ⇒ List_t 't))
                      where
                      Ok (ls, fun (ret : List_t 't) => ret)
                    
                    (* [loops::id_shared]:
                       Source: 'tests/src/loops.rs', lines 153:0-155:1 *)
                    definition id_shared
                      ('t) (ls : List_t 't) : result (List_t 't) where
                      Ok ls
                    
                    where
                      
                      (* [loops::list_nth_mut_loop_with_id]: loop 0:
                         Source: 'tests/src/loops.rs', lines 160:4-169:1 *)
                      fun list_nth_mut_loop_with_id_loop
                        ('t) (i : u32) (ls : List_t 't) :
                        result ('t × ('t ⇒ List_t 't))
                        where
                        case ls of
                        | List_Cons x tl =>
                          if i = 0 :: u32
                          then
                            let back = fun (ret : 't) => List_Cons ret tl in
                            Ok (x, back)
                          else (
                            let i1 = u32_sub i 1 :: u32 in
                            let (t, back) =
                              list_nth_mut_loop_with_id_loop i1 tl
                            in
                            let back1 =
                              fun (ret : 't) =>
                                let tl1 = back ret in List_Cons x tl1
                            in
                            Ok (t, back1))
                        | List_Nil => Fail Failure
                      
                      (* [loops::list_nth_mut_loop_with_id]:
                         Source: 'tests/src/loops.rs', lines 158:0-169:1 *)
                      definition list_nth_mut_loop_with_id
                        ('t) (ls : List_t 't) (i : u32) :
                        result ('t × ('t ⇒ List_t 't))
                        where
                        let (ls1, id_mut_back) = id_mut ls in
                        let (t, back) = list_nth_mut_loop_with_id_loop i ls1 in
                        let back1 =
                          fun (ret : 't) => let l = back ret in id_mut_back l
                        in
                        Ok (t, back1)
                      
                      where
                        
                        (* [loops::list_nth_shared_loop_with_id]: loop 0:
                           Source: 'tests/src/loops.rs', lines 174:4-183:1 *)
                        fun list_nth_shared_loop_with_id_loop
                          ('t) (i : u32) (ls : List_t 't) : result 't where
                          case ls of
                          | List_Cons x tl =>
                            if i = 0 :: u32
                            then Ok x
                            else (
                              let i1 = u32_sub i 1 :: u32 in
                              list_nth_shared_loop_with_id_loop i1 tl)
                          | List_Nil => Fail Failure
                        
                        (* [loops::list_nth_shared_loop_with_id]:
                           Source: 'tests/src/loops.rs', lines 172:0-183:1 *)
                        definition list_nth_shared_loop_with_id
                          ('t) (ls : List_t 't) (i : u32) : result 't where
                          let ls1 = id_shared ls in
                          list_nth_shared_loop_with_id_loop i ls1
                        
                        where
                          
                          (* [loops::list_nth_mut_loop_pair]: loop 0:
                             Source: 'tests/src/loops.rs', lines 194:8-194:24 *)
                          fun list_nth_mut_loop_pair_loop
                            ('t) (ls0 : List_t 't) (ls1 : List_t 't) 
                            (i : u32) :
                            result (('t × 't) × ('t ⇒ List_t 't) × ('t ⇒
                              List_t 't))
                            where
                            case ls0 of
                            | List_Cons x0 tl0 =>
                              case ls1 of
                              | List_Cons x1 tl1 =>
                                if i = 0 :: u32
                                then
                                  let back'a =
                                    fun (ret : 't) => List_Cons ret tl0
                                  in
                                  let back'b =
                                    fun (ret : 't) => List_Cons ret tl1
                                  in
                                  Ok ((x0, x1), back'a, back'b)
                                else (
                                  let i1 = u32_sub i 1 :: u32 in
                                  let (p, back'a, back'b) =
                                    list_nth_mut_loop_pair_loop tl0 tl1 i1
                                  in
                                  let back'a1 =
                                    fun (ret : 't) =>
                                      let tl01 = back'a ret in
                                      List_Cons x0 tl01
                                  in
                                  let back'b1 =
                                    fun (ret : 't) =>
                                      let tl11 = back'b ret in
                                      List_Cons x1 tl11
                                  in
                                  Ok (p, back'a1, back'b1))
                              | List_Nil => Fail Failure
                            | List_Nil => Fail Failure
                          
                          (* [loops::list_nth_mut_loop_pair]:
                             Source: 'tests/src/loops.rs', lines 188:0-209:1 *)
                          definition list_nth_mut_loop_pair
                            ('t) (ls0 : List_t 't) (ls1 : List_t 't) 
                            (i : u32) :
                            result (('t × 't) × ('t ⇒ List_t 't) × ('t ⇒
                              List_t 't))
                            where
                            list_nth_mut_loop_pair_loop ls0 ls1 i
                          
                          where
                            
                            (* [loops::list_nth_shared_loop_pair]: loop 0:
                               Source: 'tests/src/loops.rs', lines 218:8-218:24 *)
                            fun list_nth_shared_loop_pair_loop
                              ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                              (i : u32) :
                              result ('t × 't)
                              where
                              case ls0 of
                              | List_Cons x0 tl0 =>
                                case ls1 of
                                | List_Cons x1 tl1 =>
                                  if i = 0 :: u32
                                  then Ok (x0, x1)
                                  else (
                                    let i1 = u32_sub i 1 :: u32 in
                                    list_nth_shared_loop_pair_loop tl0 tl1 i1)
                                | List_Nil => Fail Failure
                              | List_Nil => Fail Failure
                            
                            (* [loops::list_nth_shared_loop_pair]:
                               Source: 'tests/src/loops.rs', lines 212:0-233:1 *)
                            definition list_nth_shared_loop_pair
                              ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                              (i : u32) :
                              result ('t × 't)
                              where
                              list_nth_shared_loop_pair_loop ls0 ls1 i
                            
                            where
                              
                              (* [loops::list_nth_mut_loop_pair_merge]: loop 0:
                                 Source: 'tests/src/loops.rs', lines 242:4-252:1 *)
                              fun list_nth_mut_loop_pair_merge_loop
                                ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                (i : u32) :
                                result (('t × 't) × (('t × 't) ⇒ ((List_t
                                  't) × (List_t 't))))
                                where
                                case ls0 of
                                | List_Cons x0 tl0 =>
                                  case ls1 of
                                  | List_Cons x1 tl1 =>
                                    if i = 0 :: u32
                                    then
                                      let back =
                                        fun (ret : ('t × 't)) =>
                                          let (t, t1) = ret in
                                          (List_Cons t tl0, List_Cons t1 tl1)
                                      in
                                      Ok ((x0, x1), back)
                                    else (
                                      let i1 = u32_sub i 1 :: u32 in
                                      let (p, back) =
                                        list_nth_mut_loop_pair_merge_loop tl0
                                          tl1 i1
                                      in
                                      let back1 =
                                        fun (ret : ('t × 't)) =>
                                          let (tl01, tl11) = back ret in
                                          (List_Cons x0 tl01, List_Cons x1
                                            tl11)
                                      in
                                      Ok (p, back1))
                                  | List_Nil => Fail Failure
                                | List_Nil => Fail Failure
                              
                              (* [loops::list_nth_mut_loop_pair_merge]:
                                 Source: 'tests/src/loops.rs', lines 237:0-252:1 *)
                              definition list_nth_mut_loop_pair_merge
                                ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                (i : u32) :
                                result (('t × 't) × (('t × 't) ⇒ ((List_t
                                  't) × (List_t 't))))
                                where
                                list_nth_mut_loop_pair_merge_loop ls0 ls1 i
                              
                              where
                                
                                (* [loops::list_nth_shared_loop_pair_merge]: loop 0:
                                   Source: 'tests/src/loops.rs', lines 260:4-270:1 *)
                                fun list_nth_shared_loop_pair_merge_loop
                                  ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                  (i : u32) :
                                  result ('t × 't)
                                  where
                                  case ls0 of
                                  | List_Cons x0 tl0 =>
                                    case ls1 of
                                    | List_Cons x1 tl1 =>
                                      if i = 0 :: u32
                                      then Ok (x0, x1)
                                      else (
                                        let i1 = u32_sub i 1 :: u32 in
                                        list_nth_shared_loop_pair_merge_loop
                                          tl0 tl1 i1)
                                    | List_Nil => Fail Failure
                                  | List_Nil => Fail Failure
                                
                                (* [loops::list_nth_shared_loop_pair_merge]:
                                   Source: 'tests/src/loops.rs', lines 255:0-270:1 *)
                                definition list_nth_shared_loop_pair_merge
                                  ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                  (i : u32) :
                                  result ('t × 't)
                                  where
                                  list_nth_shared_loop_pair_merge_loop ls0 ls1
                                    i
                                
                                where
                                  
                                  (* [loops::list_nth_mut_shared_loop_pair]: loop 0:
                                     Source: 'tests/src/loops.rs', lines 278:4-288:1 *)
                                  fun list_nth_mut_shared_loop_pair_loop
                                    ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                    (i : u32) :
                                    result (('t × 't) × ('t ⇒ List_t 't))
                                    where
                                    case ls0 of
                                    | List_Cons x0 tl0 =>
                                      case ls1 of
                                      | List_Cons x1 tl1 =>
                                        if i = 0 :: u32
                                        then
                                          let back =
                                            fun (ret : 't) => List_Cons ret tl0
                                          in
                                          Ok ((x0, x1), back)
                                        else (
                                          let i1 = u32_sub i 1 :: u32 in
                                          let (p, back) =
                                            list_nth_mut_shared_loop_pair_loop
                                              tl0 tl1 i1
                                          in
                                          let back1 =
                                            fun (ret : 't) =>
                                              let tl01 = back ret in
                                              List_Cons x0 tl01
                                          in
                                          Ok (p, back1))
                                      | List_Nil => Fail Failure
                                    | List_Nil => Fail Failure
                                  
                                  (* [loops::list_nth_mut_shared_loop_pair]:
                                     Source: 'tests/src/loops.rs', lines 273:0-288:1 *)
                                  definition list_nth_mut_shared_loop_pair
                                    ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                    (i : u32) :
                                    result (('t × 't) × ('t ⇒ List_t 't))
                                    where
                                    list_nth_mut_shared_loop_pair_loop ls0 ls1
                                      i
                                  
                                  where
                                    
                                    (* [loops::list_nth_mut_shared_loop_pair_merge]: loop 0:
                                       Source: 'tests/src/loops.rs', lines 297:4-307:1 *)
                                    fun
                                      list_nth_mut_shared_loop_pair_merge_loop
                                      ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                      (i : u32) :
                                      result (('t × 't) × ('t ⇒ List_t 't))
                                      where
                                      case ls0 of
                                      | List_Cons x0 tl0 =>
                                        case ls1 of
                                        | List_Cons x1 tl1 =>
                                          if i = 0 :: u32
                                          then
                                            let back =
                                              fun (ret : 't) => List_Cons ret
                                                tl0
                                            in
                                            Ok ((x0, x1), back)
                                          else (
                                            let i1 = u32_sub i 1 :: u32 in
                                            let (p, back) =
                                              list_nth_mut_shared_loop_pair_merge_loop
                                                tl0 tl1 i1
                                            in
                                            let back1 =
                                              fun (ret : 't) =>
                                                let tl01 = back ret in
                                                List_Cons x0 tl01
                                            in
                                            Ok (p, back1))
                                        | List_Nil => Fail Failure
                                      | List_Nil => Fail Failure
                                    
                                    (* [loops::list_nth_mut_shared_loop_pair_merge]:
                                       Source: 'tests/src/loops.rs', lines 292:0-307:1 *)
                                    definition
                                      list_nth_mut_shared_loop_pair_merge
                                      ('t) (ls0 : List_t 't) (ls1 : List_t 't)
                                      (i : u32) :
                                      result (('t × 't) × ('t ⇒ List_t 't))
                                      where
                                      list_nth_mut_shared_loop_pair_merge_loop
                                        ls0 ls1 i
                                    
                                    where
                                      
                                      (* [loops::list_nth_shared_mut_loop_pair]: loop 0:
                                         Source: 'tests/src/loops.rs', lines 316:4-326:1 *)
                                      fun list_nth_shared_mut_loop_pair_loop
                                        ('t) (ls0 : List_t 't)
                                        (ls1 : List_t 't) (i : u32) :
                                        result (('t × 't) × ('t ⇒ List_t
                                          't))
                                        where
                                        case ls0 of
                                        | List_Cons x0 tl0 =>
                                          case ls1 of
                                          | List_Cons x1 tl1 =>
                                            if i = 0 :: u32
                                            then
                                              let back =
                                                fun (ret : 't) => List_Cons ret
                                                  tl1
                                              in
                                              Ok ((x0, x1), back)
                                            else (
                                              let i1 = u32_sub i 1 :: u32 in
                                              let (p, back) =
                                                list_nth_shared_mut_loop_pair_loop
                                                  tl0 tl1 i1
                                              in
                                              let back1 =
                                                fun (ret : 't) =>
                                                  let tl11 = back ret in
                                                  List_Cons x1 tl11
                                              in
                                              Ok (p, back1))
                                          | List_Nil => Fail Failure
                                        | List_Nil => Fail Failure
                                      
                                      (* [loops::list_nth_shared_mut_loop_pair]:
                                         Source: 'tests/src/loops.rs', lines 311:0-326:1 *)
                                      definition list_nth_shared_mut_loop_pair
                                        ('t) (ls0 : List_t 't)
                                        (ls1 : List_t 't) (i : u32) :
                                        result (('t × 't) × ('t ⇒ List_t
                                          't))
                                        where
                                        list_nth_shared_mut_loop_pair_loop ls0
                                          ls1 i
                                      
                                      where
                                        
                                        (* [loops::list_nth_shared_mut_loop_pair_merge]: loop 0:
                                           Source: 'tests/src/loops.rs', lines 335:4-345:1 *)
                                        fun
                                          list_nth_shared_mut_loop_pair_merge_loop
                                          ('t) (ls0 : List_t 't)
                                          (ls1 : List_t 't) (i : u32) :
                                          result (('t × 't) × ('t ⇒ List_t
                                            't))
                                          where
                                          case ls0 of
                                          | List_Cons x0 tl0 =>
                                            case ls1 of
                                            | List_Cons x1 tl1 =>
                                              if i = 0 :: u32
                                              then
                                                let back =
                                                  fun (ret : 't) => List_Cons
                                                    ret tl1
                                                in
                                                Ok ((x0, x1), back)
                                              else (
                                                let i1 = u32_sub i 1 :: u32 in
                                                let (p, back) =
                                                  list_nth_shared_mut_loop_pair_merge_loop
                                                    tl0 tl1 i1
                                                in
                                                let back1 =
                                                  fun (ret : 't) =>
                                                    let tl11 = back ret in
                                                    List_Cons x1 tl11
                                                in
                                                Ok (p, back1))
                                            | List_Nil => Fail Failure
                                          | List_Nil => Fail Failure
                                        
                                        (* [loops::list_nth_shared_mut_loop_pair_merge]:
                                           Source: 'tests/src/loops.rs', lines 330:0-345:1 *)
                                        definition
                                          list_nth_shared_mut_loop_pair_merge
                                          ('t) (ls0 : List_t 't)
                                          (ls1 : List_t 't) (i : u32) :
                                          result (('t × 't) × ('t ⇒ List_t
                                            't))
                                          where
                                          list_nth_shared_mut_loop_pair_merge_loop
                                            ls0 ls1 i
                                        
                                        where
                                          
                                          (* [loops::ignore_input_mut_borrow]: loop 0:
                                             Source: 'tests/src/loops.rs', lines 350:4-352:5 *)
                                          fun ignore_input_mut_borrow_loop
                                            (i : u32) : result unit where
                                            if u32_gt i 0 :: u32
                                            then (
                                              let i1 = u32_sub i 1 :: u32 in
                                              ignore_input_mut_borrow_loop i1)
                                            else Ok ()
                                          
                                          (* [loops::ignore_input_mut_borrow]:
                                             Source: 'tests/src/loops.rs', lines 349:0-353:1 *)
                                          definition ignore_input_mut_borrow
                                            (_a : u32) (i : u32) :
                                            result u32
                                            where
                                            let _ =
                                              ignore_input_mut_borrow_loop i
                                            in
                                            Ok _a
                                          
                                          where
                                            
                                            (* [loops::incr_ignore_input_mut_borrow]: loop 0:
                                               Source: 'tests/src/loops.rs', lines 359:4-361:5 *)
                                            fun
                                              incr_ignore_input_mut_borrow_loop
                                              (i : u32) : result unit where
                                              if u32_gt i 0 :: u32
                                              then (
                                                let i1 = u32_sub i 1 :: u32 in
                                                incr_ignore_input_mut_borrow_loop
                                                  i1)
                                              else Ok ()
                                            
                                            (* [loops::incr_ignore_input_mut_borrow]:
                                               Source: 'tests/src/loops.rs', lines 357:0-362:1 *)
                                            definition
                                              incr_ignore_input_mut_borrow
                                              (a : u32) (i : u32) :
                                              result u32
                                              where
                                              let a1 = u32_add a 1 :: u32 in
                                              let _ =
                                                incr_ignore_input_mut_borrow_loop
                                                  i
                                              in
                                              Ok a1
                                            
                                            where
                                              
                                              (* [loops::ignore_input_shared_borrow]: loop 0:
                                                 Source: 'tests/src/loops.rs', lines 367:4-369:5 *)
                                              fun
                                                ignore_input_shared_borrow_loop
                                                (i : u32) : result unit where
                                                if u32_gt i 0 :: u32
                                                then (
                                                  let i1 = u32_sub i 1 :: u32
                                                  in
                                                  ignore_input_shared_borrow_loop
                                                    i1)
                                                else Ok ()
                                              
                                              (* [loops::ignore_input_shared_borrow]:
                                                 Source: 'tests/src/loops.rs', lines 366:0-370:1 *)
                                              definition
                                                ignore_input_shared_borrow
                                                (_a : u32) (i : u32) :
                                                result u32
                                                where
                                                let _ =
                                                  ignore_input_shared_borrow_loop
                                                    i
                                                in
                                                Ok _a
                                              
end
