(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [mini_tree] *)

theory MiniTree
  imports
    Aeneas.Primitives
    begin
\m(* [mini_tree::Node]
   Source: 'tests/src/mini_tree.rs', lines 3:0-5:1 *)