(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [polonius_list] *)

theory PoloniusList
  imports
    Aeneas.Primitives
    begin
\m(* [polonius_list::List]
   Source: 'tests/src/polonius_list.rs', lines 6:0-9:1 *)
datatype List_t (''t') =
| List_Cons 't of  List_t 't ⇒ List_t 't
| List_Nil List_t 't
where
  
  (* [polonius_list::get_list_at_x]:
     Source: 'tests/src/polonius_list.rs', lines 16:0-30:1 *)
  fun get_list_at_x
    (ls : List_t u32) (x : u32) :
    result ((List_t u32) × (List_t u32 ⇒ List_t u32))
    where
    case ls of
    | List_Cons hd tl =>
      if hd = x
      then Ok (ls, fun (ret : List_t u32) => ret)
      else (
        let (l, get_list_at_x_back) = get_list_at_x tl x in
        let back =
          fun (ret : List_t u32) =>
            let tl1 = get_list_at_x_back ret in List_Cons hd tl1
        in
        Ok (l, back))
    | List_Nil => Ok (List_Nil, fun (ret : List_t u32) => ret)
  
end
