(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rename_attribute] *)

theory RenameAttribute
  imports
    Aeneas.Primitives
    begin
\m
(* Trait declaration: [rename_attribute::BoolTrait]
   Source: 'tests/src/rename_attribute.rs', lines 9:0-19:1 *)
record BoolTest_t (''self') =
  getTest :: 'self ⇒ result bool
  retTest :: 'self ⇒ result bool

(* [rename_attribute::BoolTrait::ret_true]:
   Source: 'tests/src/rename_attribute.rs', lines 16:4-18:5 *)
definition boolTrait_retTest_default ('self) (self : 'self) : result bool where
  Ok True

(* [rename_attribute::{rename_attribute::BoolTrait for bool}::get_bool]:
   Source: 'tests/src/rename_attribute.rs', lines 23:4-25:5 *)
definition boolTraitBool_getTest (self : bool) : result bool where
  Ok self

(* [rename_attribute::{rename_attribute::BoolTrait for bool}::ret_true]:
   Source: 'tests/src/rename_attribute.rs', lines 22:0-26:1 *)
definition boolTraitBool_retTest (self : bool) : result bool where
  Ok True

(* Trait implementation: [rename_attribute::{rename_attribute::BoolTrait for bool}]
   Source: 'tests/src/rename_attribute.rs', lines 22:0-26:1 *)
definition boolImpl :: BoolTest_t bool where "boolImpl = (|
  getTest = boolTraitBool_getTest
  retTest = boolTraitBool_retTest
|)"

(* [rename_attribute::test_bool_trait]:
   Source: 'tests/src/rename_attribute.rs', lines 29:0-31:1 *)
definition boolFn (''t') (x : bool) : result bool where
  let b = boolTraitBool_getTest x in
  if b then boolTraitBool_retTest x else Ok False
(* [rename_attribute::SimpleEnum]
   Source: 'tests/src/rename_attribute.rs', lines 37:0-42:1 *)
datatype VariantsTest_t =
| VariantsTest_Variant1 VariantsTest_t
| VariantsTest_SecondVariant VariantsTest_t
| VariantsTest_ThirdVariant VariantsTest_t(* [rename_attribute::Foo]
                                             Source: 'tests/src/rename_attribute.rs', lines 45:0-48:1 *)
record StructTest_t = fieldTest : u32
(* [rename_attribute::C]
   Source: 'tests/src/rename_attribute.rs', lines 51:0-51:28 *)
definition const_test_body :: result u32 where
  "const_test_body = let i = u32_add 100 :: u32 10 :: u32 in u32_add i 1 :: u32"
definition const_test :: u32 where "const_test = get_result const_test_body"

(* [rename_attribute::CA]
   Source: 'tests/src/rename_attribute.rs', lines 54:0-54:23 *)
definition const_aeneas11_body :: result u32 where
  "const_aeneas11_body = u32_add 10 :: u32 1 :: u32"
definition const_aeneas11 :: u32 where
  "const_aeneas11 = get_result const_aeneas11_body"

where
  
  (* [rename_attribute::factorial]:
     Source: 'tests/src/rename_attribute.rs', lines 57:0-63:1 *)
  fun factfn (n : u64) : result u64 where
    if u64_le n 1 :: u64
    then Ok 1 :: u64
    else (let i = u64_sub n 1 :: u64 in let i1 = factfn i in u64_mul n i1)
  
  where
    
    (* [rename_attribute::sum]: loop 0:
       Source: 'tests/src/rename_attribute.rs', lines 69:4-72:5 *)
    fun no_borrows_sum_loop (max : u32) (i : u32) (s : u32) : result u32 where
      if u32_lt i max
      then (
        let s1 = u32_add s i in
        let i1 = u32_add i 1 :: u32 in
        no_borrows_sum_loop max i1 s1)
      else u32_mul s 2 :: u32
    
    (* [rename_attribute::sum]:
       Source: 'tests/src/rename_attribute.rs', lines 66:0-76:1 *)
    definition no_borrows_sum (max : u32) : result u32 where
      no_borrows_sum_loop max 0 :: u32 0 :: u32
    
end
