(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [switch_test] *)

theory SwitchTest
  imports
    Aeneas.Primitives
    begin
\m
(* [switch_test::match_u32]:
   Source: 'tests/src/switch_test.rs', lines 4:0-10:1 *)
definition match_u32 (x : u32) : result u32 where
  case x of
  | 0 :: u32 => Ok 0 :: u32
  | 1 :: u32 => Ok 1 :: u32
  | _ => Ok 2 :: u32

end
