(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [traits] *)

theory Traits
  imports
    Aeneas.Primitives
    begin
\m(* [core::result::Result]
   Source: '/rustc/library/core/src/result.rs', lines 548:0-548:21
   Name pattern: [core::result::Result] *)
datatype core_result_Result_t (''t') (''e') =
| Core_result_Result_Ok 't ⇒ core_result_Result_t 't 'e
| Core_result_Result_Err 'e ⇒ core_result_Result_t 't 'e
(* Trait declaration: [traits::BoolTrait]
   Source: 'tests/src/traits.rs', lines 3:0-11:1 *)
record BoolTrait_t (''self') =
  get_bool :: 'self ⇒ result bool
  ret_true :: 'self ⇒ result bool

(* [traits::BoolTrait::ret_true]:
   Source: 'tests/src/traits.rs', lines 8:4-10:5 *)
definition boolTrait_ret_true_default
  ('self) (self : 'self) : result bool where
  Ok True

(* [traits::{traits::BoolTrait for bool}::get_bool]:
   Source: 'tests/src/traits.rs', lines 14:4-16:5 *)
definition boolTraitBool_get_bool (self : bool) : result bool where
  Ok self

(* [traits::{traits::BoolTrait for bool}::ret_true]:
   Source: 'tests/src/traits.rs', lines 13:0-17:1 *)
definition boolTraitBool_ret_true (self : bool) : result bool where
  Ok True

(* Trait implementation: [traits::{traits::BoolTrait for bool}]
   Source: 'tests/src/traits.rs', lines 13:0-17:1 *)
definition boolTraitBool :: BoolTrait_t bool where "boolTraitBool = (|
  get_bool = boolTraitBool_get_bool
  ret_true = boolTraitBool_ret_true
|)"

(* [traits::test_bool_trait_bool]:
   Source: 'tests/src/traits.rs', lines 19:0-21:1 *)
definition test_bool_trait_bool (x : bool) : result bool where
  let b = boolTraitBool_get_bool x in
  if b then boolTraitBool_ret_true x else Ok False

(* [traits::{traits::BoolTrait for core::option::Option<T>}::get_bool]:
   Source: 'tests/src/traits.rs', lines 25:4-30:5 *)
definition boolTraitOption_get_bool ('t) (self : option 't) : result bool where
  case self of | None => Ok False | Some _ => Ok True

(* [traits::{traits::BoolTrait for core::option::Option<T>}::ret_true]:
   Source: 'tests/src/traits.rs', lines 24:0-31:1 *)
definition boolTraitOption_ret_true ('t) (self : option 't) : result bool where
  Ok True

(* Trait implementation: [traits::{traits::BoolTrait for core::option::Option<T>}]
   Source: 'tests/src/traits.rs', lines 24:0-31:1 *)
definition boolTraitOption (''t') :: BoolTrait_t (option 't)
  where "boolTraitOption = (|
  get_bool = boolTraitOption_get_bool
  ret_true = boolTraitOption_ret_true
|)"

(* [traits::test_bool_trait_option]:
   Source: 'tests/src/traits.rs', lines 33:0-35:1 *)
definition test_bool_trait_option ('t) (x : option 't) : result bool where
  let b = boolTraitOption_get_bool x in
  if b then boolTraitOption_ret_true x else Ok False

(* [traits::test_bool_trait]:
   Source: 'tests/src/traits.rs', lines 37:0-39:1 *)
definition test_bool_trait
  ('t) ('boolTraitInst : BoolTrait_t 't') (x : 't) : result bool where
  boolTraitInst.get_bool x

(* Trait declaration: [traits::ToU64]
   Source: 'tests/src/traits.rs', lines 41:0-43:1 *)
record ToU64_t (''self') = to_u64 :: 'self ⇒ result u64

(* [traits::{traits::ToU64 for u64}::to_u64]:
   Source: 'tests/src/traits.rs', lines 46:4-48:5 *)
definition toU64U64_to_u64 (self : u64) : result u64 where
  Ok self

(* Trait implementation: [traits::{traits::ToU64 for u64}]
   Source: 'tests/src/traits.rs', lines 45:0-49:1 *)
definition toU64U64 :: ToU64_t u64 where "toU64U64 = (|
  to_u64 = toU64U64_to_u64
|)"

(* [traits::{traits::ToU64 for (A, A)}::to_u64]:
   Source: 'tests/src/traits.rs', lines 52:4-54:5 *)
definition toU64Pair_to_u64
  ('a) ('toU64Inst : ToU64_t 'a') (self : ('a × 'a)) : result u64 where
  let (t, t1) = self in
  let i = toU64Inst.to_u64 t in
  let i1 = toU64Inst.to_u64 t1 in
  u64_add i i1

(* Trait implementation: [traits::{traits::ToU64 for (A, A)}]
   Source: 'tests/src/traits.rs', lines 51:0-55:1 *)
definition toU64Pair ('a) ('toU64Inst : ToU64_t 'a') :: ToU64_t ('a × 'a)
  where "toU64Pair = (|
  to_u64 = toU64Pair_to_u64 toU64Inst
|)"

(* [traits::f]:
   Source: 'tests/src/traits.rs', lines 57:0-59:1 *)
definition f
  ('t) ('toU64Inst : ToU64_t 't') (x : ('t × 't)) : result u64 where
  toU64Pair_to_u64 toU64Inst x

(* [traits::g]:
   Source: 'tests/src/traits.rs', lines 61:0-66:1 *)
definition g
  ('t) ('toU64PairInst : ToU64_t ('t × 't)') (x : ('t × 't)) :
  result u64
  where
  toU64PairInst.to_u64 x

(* [traits::h0]:
   Source: 'tests/src/traits.rs', lines 68:0-70:1 *)
definition h0 (x : u64) : result u64 where
  toU64U64_to_u64 x
(* [traits::Wrapper]
   Source: 'tests/src/traits.rs', lines 72:0-74:1 *)
record Wrapper_t (''t') = x : 't
(* [traits::{traits::ToU64 for traits::Wrapper<T>}::to_u64]:
   Source: 'tests/src/traits.rs', lines 77:4-79:5 *)
definition toU64traitsWrapper_to_u64
  ('t) ('toU64Inst : ToU64_t 't') (self : Wrapper_t 't) : result u64 where
  toU64Inst.to_u64 x self

(* Trait implementation: [traits::{traits::ToU64 for traits::Wrapper<T>}]
   Source: 'tests/src/traits.rs', lines 76:0-80:1 *)
definition toU64traitsWrapper ('t) ('toU64Inst : ToU64_t 't') :: ToU64_t
  (Wrapper_t 't) where "toU64traitsWrapper = (|
  to_u64 = toU64traitsWrapper_to_u64 toU64Inst
|)"

(* [traits::h1]:
   Source: 'tests/src/traits.rs', lines 82:0-84:1 *)
definition h1 (x : Wrapper_t u64) : result u64 where
  toU64traitsWrapper_to_u64 toU64U64 x

(* [traits::h2]:
   Source: 'tests/src/traits.rs', lines 86:0-88:1 *)
definition h2
  ('t) ('toU64Inst : ToU64_t 't') (x : Wrapper_t 't) : result u64 where
  toU64traitsWrapper_to_u64 toU64Inst x

(* Trait declaration: [traits::ToType]
   Source: 'tests/src/traits.rs', lines 90:0-92:1 *)
record ToType_t (''self') (''t') = to_type :: 'self ⇒ result 't

(* [traits::{traits::ToType<bool> for u64}::to_type]:
   Source: 'tests/src/traits.rs', lines 95:4-97:5 *)
definition toTypeU64Bool_to_type (self : u64) : result bool where
  Ok (u64_gt self 0 :: u64)

(* Trait implementation: [traits::{traits::ToType<bool> for u64}]
   Source: 'tests/src/traits.rs', lines 94:0-98:1 *)
definition toTypeU64Bool :: ToType_t u64 bool where "toTypeU64Bool = (|
  to_type = toTypeU64Bool_to_type
|)"

(* Trait declaration: [traits::OfType]
   Source: 'tests/src/traits.rs', lines 100:0-104:1 *)
record OfType_t (''self') = of_type :: 't ⇒ result 'self

(* [traits::h3]:
   Source: 'tests/src/traits.rs', lines 106:0-108:1 *)
definition h3
  ('t1) ('t2) ('ofTypeInst : OfType_t 't1') ('toTypeInst : ToType_t 't2 't1')
  (y : 't2) :
  result 't1
  where
  ofTypeInst.of_type toTypeInst y

(* Trait declaration: [traits::OfTypeBis]
   Source: 'tests/src/traits.rs', lines 111:0-118:1 *)
record OfTypeBis_t (''self') (''t') =
  toTypeInst :: ToType_t 't 'self
  of_type :: 't ⇒ result 'self

(* [traits::h4]:
   Source: 'tests/src/traits.rs', lines 120:0-122:1 *)
definition h4
  ('t1) ('t2) ('ofTypeBisInst : OfTypeBis_t 't1 't2') ('toTypeInst : ToType_t
  't2 't1') (y : 't2) :
  result 't1
  where
  ofTypeBisInst.of_type y
(* [traits::TestType]
   Source: 'tests/src/traits.rs', lines 124:0-124:26 *)
abbreviation TestType_t (''t') = 't(* [traits::{traits::TestType<T>}::test::TestType1]
                                      Source: 'tests/src/traits.rs', lines 129:8-129:30 *)
abbreviation TestType_test_TestType1_t = u64
(* [traits::{traits::TestType<T>}::test::{traits::{traits::TestType<T>}::test::TestTrait for traits::{traits::TestType<T>}::test::TestType1}::test]:
   Source: 'tests/src/traits.rs', lines 141:12-143:13 *)
definition testType_test_TestTraittraitsTestTypetestTestType1_test
  (self : TestType_test_TestType1_t) : result bool where
  Ok (u64_gt self 1 :: u64)

(* [traits::{traits::TestType<T>}::test]:
   Source: 'tests/src/traits.rs', lines 128:4-149:5 *)
definition testType_test
  ('t) ('toU64Inst : ToU64_t 't') (self : TestType_t 't) (x : 't) :
  result bool
  where
  let x1 = toU64Inst.to_u64 x in
  if u64_gt x1 0 :: u64
  then testType_test_TestTraittraitsTestTypetestTestType1_test 0 :: u64
  else Ok False

(* Trait declaration: [traits::{traits::TestType<T>}::test::TestTrait]
   Source: 'tests/src/traits.rs', lines 130:8-132:9 *)
record TestType_test_TestTrait_t (''self') = test :: 'self ⇒ result bool

(* Trait implementation: [traits::{traits::TestType<T>}::test::{traits::{traits::TestType<T>}::test::TestTrait for traits::{traits::TestType<T>}::test::TestType1}]
   Source: 'tests/src/traits.rs', lines 140:8-144:9 *)
definition testType_test_TestTraittraitsTestTypetestTestType1 ::
  TestType_test_TestTrait_t TestType_test_TestType1_t
  where "testType_test_TestTraittraitsTestTypetestTestType1 = (|
  test = testType_test_TestTraittraitsTestTypetestTestType1_test
|)"
(* [traits::BoolWrapper]
   Source: 'tests/src/traits.rs', lines 152:0-152:33 *)
abbreviation BoolWrapper_t = bool
(* [traits::{traits::ToType<T> for traits::BoolWrapper}::to_type]:
   Source: 'tests/src/traits.rs', lines 158:4-160:5 *)
definition toTypetraitsBoolWrapperT_to_type
  ('t) ('toTypeBoolTInst : ToType_t bool 't') (self : BoolWrapper_t) :
  result 't
  where
  toTypeBoolTInst.to_type self

(* Trait implementation: [traits::{traits::ToType<T> for traits::BoolWrapper}]
   Source: 'tests/src/traits.rs', lines 154:0-161:1 *)
definition toTypetraitsBoolWrapperT ('t) ('toTypeBoolTInst : ToType_t bool 't')
  :: ToType_t BoolWrapper_t 't where "toTypetraitsBoolWrapperT = (|
  to_type = toTypetraitsBoolWrapperT_to_type toTypeBoolTInst
|)"

(* Trait declaration: [traits::WithConstTy]
   Source: 'tests/src/traits.rs', lines 163:0-174:1 *)
record WithConstTy_t (''self') (''self_v') (''self_w') =
  LEN1 :: usize
  LEN2 :: usize
  toU64Inst :: ToU64_t 'self_w
  f :: 'self_w ⇒ array u8 len ⇒ result 'self_w

(* [traits::WithConstTy::LEN2]
   Source: 'tests/src/traits.rs', lines 166:4-166:27 *)
definition with_const_ty_len2_default_body (''self') :: result usize where
  "with_const_ty_len2_default_body = Ok 32 :: usize"
definition with_const_ty_len2_default (''self') :: usize where
  "with_const_ty_len2_default = get_result (with_const_ty_len2_default_body
    'self len)"

(* [traits::{traits::WithConstTy<u8, u64, 32usize> for bool}::LEN1]
   Source: 'tests/src/traits.rs', lines 177:4-177:27 *)
definition with_const_ty_bool_u8_u6432_len1_body :: result usize where
  "with_const_ty_bool_u8_u6432_len1_body = Ok 12 :: usize"
definition with_const_ty_bool_u8_u6432_len1 :: usize where
  "with_const_ty_bool_u8_u6432_len1 = get_result
    with_const_ty_bool_u8_u6432_len1_body"

(* [traits::{traits::WithConstTy<u8, u64, 32usize> for bool}::f]:
   Source: 'tests/src/traits.rs', lines 182:4-182:42 *)
definition withConstTyBoolU8U6432_f
  (i : u64) (a : array u8 32 :: usize) : result u64 where
  Ok i

(* Trait implementation: [traits::{traits::WithConstTy<u8, u64, 32usize> for bool}]
   Source: 'tests/src/traits.rs', lines 176:0-183:1 *)
definition withConstTyBoolU8U6432 :: WithConstTy_t bool u8 u64 32 :: usize
  where "withConstTyBoolU8U6432 = (|
  LEN1 = with_const_ty_bool_u8_u6432_len1
  LEN2 = with_const_ty_len2_default bool 32 :: usize
  toU64Inst = toU64U64
  f = withConstTyBoolU8U6432_f
|)"

(* [traits::use_with_const_ty1]:
   Source: 'tests/src/traits.rs', lines 185:0-187:1 *)
definition use_with_const_ty1
  ('h) ('clause1_v) ('clause1_w) ('withConstTyInst : WithConstTy_t 'h
  'clause1_v 'clause1_w len') :
  result usize
  where
  Ok withConstTyInst.LEN1

(* [traits::use_with_const_ty2]:
   Source: 'tests/src/traits.rs', lines 189:0-189:76 *)
definition use_with_const_ty2
  ('h) ('clause1_v) ('clause1_w) ('withConstTyInst : WithConstTy_t 'h
  'clause1_v 'clause1_w len') (t : 'clause1_w) :
  result unit
  where
  Ok ()

(* [traits::use_with_const_ty3]:
   Source: 'tests/src/traits.rs', lines 191:0-193:1 *)
definition use_with_const_ty3
  ('h) ('clause1_v) ('clause1_w) ('withConstTyInst : WithConstTy_t 'h
  'clause1_v 'clause1_w len') (x : 'clause1_w) :
  result u64
  where
  withConstTyInst.toU64Inst.to_u64 x

(* [traits::test_where1]:
   Source: 'tests/src/traits.rs', lines 195:0-195:43 *)
definition test_where1 ('t) (_x : 't) : result unit where
  Ok ()

(* [traits::test_where2]:
   Source: 'tests/src/traits.rs', lines 196:0-196:60 *)
definition test_where2
  ('t) ('clause1_w) ('withConstTyTU32Clause1_W32Inst : WithConstTy_t 't u32
  'clause1_w 32 :: usize') (_x : u32) :
  result unit
  where
  Ok ()

(* Trait declaration: [traits::ParentTrait0]
   Source: 'tests/src/traits.rs', lines 202:0-206:1 *)
record ParentTrait0_t (''self') (''self_w') =
  get_name :: 'self ⇒ result string
  get_w :: 'self ⇒ result 'self_w

(* Trait declaration: [traits::ParentTrait1]
   Source: 'tests/src/traits.rs', lines 207:0-207:25 *)
record ParentTrait1_t (''self') = unit

(* Trait declaration: [traits::ChildTrait]
   Source: 'tests/src/traits.rs', lines 208:0-208:52 *)
record ChildTrait_t (''self') (''self_clause1_w') =
  parentTrait0Inst :: ParentTrait0_t 'self 'self_clause1_w
  parentTrait1Inst :: ParentTrait1_t 'self

(* [traits::test_child_trait1]:
   Source: 'tests/src/traits.rs', lines 211:0-213:1 *)
definition test_child_trait1
  ('t) ('clause1_clause1_w) ('childTraitInst : ChildTrait_t 't
  'clause1_clause1_w') (x : 't) :
  result string
  where
  childTraitInst.parentTrait0Inst.get_name x

(* [traits::test_child_trait2]:
   Source: 'tests/src/traits.rs', lines 215:0-217:1 *)
definition test_child_trait2
  ('t) ('clause1_clause1_w) ('childTraitInst : ChildTrait_t 't
  'clause1_clause1_w') (x : 't) :
  result 'clause1_clause1_w
  where
  childTraitInst.parentTrait0Inst.get_w x

(* [traits::order1]:
   Source: 'tests/src/traits.rs', lines 221:0-221:62 *)
definition order1
  ('t) ('u) ('clause3_w) ('parentTrait0Inst : ParentTrait0_t 't 'clause3_w')
  ('parentTrait0Inst1 : ParentTrait0_t 'u 'clause3_w') :
  result unit
  where
  Ok ()

(* Trait declaration: [traits::ChildTrait1]
   Source: 'tests/src/traits.rs', lines 224:0-224:38 *)
record ChildTrait1_t (''self') = parentTrait1Inst :: ParentTrait1_t 'self

(* Trait implementation: [traits::{traits::ParentTrait1 for usize}]
   Source: 'tests/src/traits.rs', lines 226:0-226:30 *)
definition parentTrait1Usize :: ParentTrait1_t usize = ()

(* Trait implementation: [traits::{traits::ChildTrait1 for usize}]
   Source: 'tests/src/traits.rs', lines 227:0-227:29 *)
definition childTrait1Usize :: ChildTrait1_t usize where "childTrait1Usize = (|
  parentTrait1Inst = parentTrait1Usize
|)"

(* Trait declaration: [traits::Iterator]
   Source: 'tests/src/traits.rs', lines 231:0-233:1 *)
record Iterator_t (''self') (''self_item') = unit

(* Trait declaration: [traits::IntoIterator]
   Source: 'tests/src/traits.rs', lines 235:0-241:1 *)
record IntoIterator_t (''self') (''self_item') (''self_into_iter') =
  iteratorInst :: Iterator_t 'self_into_iter 'self_item
  into_iter :: 'self ⇒ result 'self_into_iter

(* Trait declaration: [traits::FromResidual]
   Source: 'tests/src/traits.rs', lines 252:0-252:24 *)
record FromResidual_t (''self') (''t') = unit

(* Trait declaration: [traits::Try]
   Source: 'tests/src/traits.rs', lines 248:0-250:1 *)
record Try_t (''self') (''self_residual') =
  fromResidualInst :: FromResidual_t 'self 'self_residual

(* Trait declaration: [traits::WithTarget]
   Source: 'tests/src/traits.rs', lines 254:0-256:1 *)
record WithTarget_t (''self') (''self_target') = unit

(* Trait declaration: [traits::ParentTrait2]
   Source: 'tests/src/traits.rs', lines 258:0-260:1 *)
record ParentTrait2_t (''self') (''self_u') (''self_clause2_target') =
  withTargetInst :: WithTarget_t 'self_u 'self_clause2_target

(* Trait declaration: [traits::ChildTrait2]
   Source: 'tests/src/traits.rs', lines 262:0-264:1 *)
record ChildTrait2_t (''self') (''self_clause1_u')
  (''self_clause1_clause2_target') =
  parentTrait2Inst :: ParentTrait2_t 'self 'self_clause1_u
    'self_clause1_clause2_target
  convert :: 'self_clause1_u ⇒ result 'self_clause1_clause2_target

(* Trait implementation: [traits::{traits::WithTarget<u32> for u32}]
   Source: 'tests/src/traits.rs', lines 266:0-268:1 *)
definition withTargetU32U32 :: WithTarget_t u32 u32 = ()

(* Trait implementation: [traits::{traits::ParentTrait2<u32, u32> for u32}]
   Source: 'tests/src/traits.rs', lines 270:0-272:1 *)
definition parentTrait2U32U32U32 :: ParentTrait2_t u32 u32 u32
  where "parentTrait2U32U32U32 = (|
  withTargetInst = withTargetU32U32
|)"

(* [traits::{traits::ChildTrait2<u32, u32> for u32}::convert]:
   Source: 'tests/src/traits.rs', lines 275:4-277:5 *)
definition childTrait2U32U32U32_convert (x : u32) : result u32 where
  Ok x

(* Trait implementation: [traits::{traits::ChildTrait2<u32, u32> for u32}]
   Source: 'tests/src/traits.rs', lines 274:0-278:1 *)
definition childTrait2U32U32U32 :: ChildTrait2_t u32 u32 u32
  where "childTrait2U32U32U32 = (|
  parentTrait2Inst = parentTrait2U32U32U32
  convert = childTrait2U32U32U32_convert
|)"

(* Trait declaration: [traits::CFnOnce]
   Source: 'tests/src/traits.rs', lines 288:0-292:1 *)
record CFnOnce_t (''self') (''args') (''self_output') =
  call_once :: 'self ⇒ 'args ⇒ result 'self_output

(* Trait declaration: [traits::CFnMut]
   Source: 'tests/src/traits.rs', lines 294:0-296:1 *)
record CFnMut_t (''self') (''args') (''self_clause1_output') =
  cFnOnceInst :: CFnOnce_t 'self 'args 'self_clause1_output
  call_mut :: 'self ⇒ 'args ⇒ result ('self_clause1_output × 'self)

(* Trait declaration: [traits::CFn]
   Source: 'tests/src/traits.rs', lines 298:0-300:1 *)
record CFn_t (''self') (''args') (''self_clause1_clause1_output') =
  cFnMutInst :: CFnMut_t 'self 'args 'self_clause1_clause1_output
  call :: 'self ⇒ 'args ⇒ result 'self_clause1_clause1_output

(* Trait declaration: [traits::GetTrait]
   Source: 'tests/src/traits.rs', lines 302:0-305:1 *)
record GetTrait_t (''self') (''self_w') = get_w :: 'self ⇒ result 'self_w

(* [traits::test_get_trait]:
   Source: 'tests/src/traits.rs', lines 307:0-309:1 *)
definition test_get_trait
  ('t) ('clause1_w) ('getTraitInst : GetTrait_t 't 'clause1_w') (x : 't) :
  result 'clause1_w
  where
  getTraitInst.get_w x

(* Trait declaration: [traits::Trait]
   Source: 'tests/src/traits.rs', lines 312:0-314:1 *)
record Trait_t (''self') = LEN :: usize

(* [traits::{traits::Trait for @Array<T, N>}::LEN]
   Source: 'tests/src/traits.rs', lines 317:4-317:25 *)
definition trait_array_len_body (''t') :: result usize where
  "trait_array_len_body = Ok n"
definition trait_array_len (''t') :: usize where
  "trait_array_len = get_result (trait_array_len_body 't n)"

(* Trait implementation: [traits::{traits::Trait for @Array<T, N>}]
   Source: 'tests/src/traits.rs', lines 316:0-318:1 *)
definition traitArray (''t') :: Trait_t (array 't n) where "traitArray = (|
  LEN = trait_array_len 't n
|)"

(* [traits::{traits::Trait for traits::Wrapper<T>}::LEN]
   Source: 'tests/src/traits.rs', lines 321:4-321:25 *)
definition traittraits_wrapper_len_body ('t) ('traitInst : Trait_t 't')
  :: result usize where
  "traittraits_wrapper_len_body = Ok 0 :: usize"
definition traittraits_wrapper_len ('t) ('traitInst : Trait_t 't')
  :: usize where
  "traittraits_wrapper_len = get_result (traittraits_wrapper_len_body
    traitInst)"

(* Trait implementation: [traits::{traits::Trait for traits::Wrapper<T>}]
   Source: 'tests/src/traits.rs', lines 320:0-322:1 *)
definition traittraitsWrapper ('t) ('traitInst : Trait_t 't') :: Trait_t
  (Wrapper_t 't) where "traittraitsWrapper = (|
  LEN = traittraits_wrapper_len traitInst
|)"

(* [traits::use_wrapper_len]:
   Source: 'tests/src/traits.rs', lines 324:0-326:1 *)
definition use_wrapper_len ('t) ('traitInst : Trait_t 't') : result usize where
  Ok (traittraitsWrapper traitInst).LEN
(* [traits::Foo]
   Source: 'tests/src/traits.rs', lines 328:0-331:1 *)
record Foo_t (''t') (''u') = x : 't
                             y : 'u
(* [traits::{traits::Foo<T, U>}::FOO]
   Source: 'tests/src/traits.rs', lines 334:4-334:43 *)
definition foo_foo_body ('t) (''u') ('traitInst : Trait_t 't')
  :: result (core_result_Result_t 't i32) where
  "foo_foo_body = Ok (Core_result_Result_Err 0 :: i32)"
definition foo_foo ('t) (''u') ('traitInst : Trait_t 't')
  :: core_result_Result_t 't i32 where
  "foo_foo = get_result (foo_foo_body 'u traitInst)"

(* [traits::use_foo1]:
   Source: 'tests/src/traits.rs', lines 337:0-339:1 *)
definition use_foo1
  ('t) (''u') ('traitInst : Trait_t 't') :
  result (core_result_Result_t 't i32)
  where
  Ok (foo_foo 'u traitInst)

(* [traits::use_foo2]:
   Source: 'tests/src/traits.rs', lines 341:0-343:1 *)
definition use_foo2
  (''t') ('u) ('traitInst : Trait_t 'u') :
  result (core_result_Result_t 'u i32)
  where
  Ok (foo_foo 't traitInst)

end
