(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [vec] *)

theory Vec
  imports
    Aeneas.Primitives
    begin
\m
(* [alloc::vec::{alloc::vec::Vec<T>}::extend_from_slice]:
   Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3167:4-3167:52
   Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::extend_from_slice] *)
axiomatization alloc_vec_Vec_extend_from_slice ::
  ('t) (''a') ('corecloneCloneInst : core_clone_Clone 't') "alloc_vec_Vec 't
                                                             ⇒ slice 't ⇒
                                                             result
                                                             (alloc_vec_Vec
                                                             't)"

(* [alloc::vec::from_elem]:
   Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3320:0-3320:55
   Name pattern: [alloc::vec::from_elem] *)
axiomatization alloc_vec_from_elem ::
  ('t) ('corecloneCloneInst : core_clone_Clone 't') "'t ⇒ usize ⇒ result
                                                      (alloc_vec_Vec 't)"

(* [vec::use_extend_from_slice]:
   Source: 'tests/src/vec.rs', lines 5:0-7:1 *)
definition use_extend_from_slice
  ('t) ('corecloneCloneInst : core_clone_Clone 't') (v : alloc_vec_Vec 't)
  (s : slice 't) :
  result (alloc_vec_Vec 't)
  where
  alloc_vec_Vec_extend_from_slice alloc_alloc_Global corecloneCloneInst v s

(* [vec::use_alloc_with_capacity]:
   Source: 'tests/src/vec.rs', lines 9:0-11:1 *)
definition use_alloc_with_capacity
  (''t') (n : usize) : result (alloc_vec_Vec 't) where
  Ok (alloc_vec_Vec_with_capacity 't n)

(* [vec::from_elem]:
   Source: 'tests/src/vec.rs', lines 13:0-15:1 *)
definition from_elem
  ('t) ('corecloneCloneInst : core_clone_Clone 't') (x : 't) (n : usize) :
  result (alloc_vec_Vec 't)
  where
  alloc_vec_from_elem corecloneCloneInst x n

end
